TerjeKir/weiss

src/bitboards.c, src/board.c, src/evaluate.c, src/makefile, src/search.c, src/uci.c
- Replaced zeroing loops with memset (gcc was replacing them with a library call anyway, I assume memset)
- Removed some zeroing loops as the arrays would be initialized to zero anyway
- Removed unroll loops, no longer seems to give any speed up
- GetInput now removes newline/carriage return from the end of the string
=> Small improvements

src/attack.c, src/bitboards.c, src/board.c, src/fathom/stdendian.h, src/fathom/tbchess.c, src/fathom/tbconfig.h, src/hashkeys.c, src/makemove.c, src/psqt.c, src/search.c, src/tests.c, src/types.h
Removed all trailing whitespace.
=> VS Code set to remove whitespace

src/cli.c, src/defs.h, src/search.c, src/syzygy.c, src/uci.c
Since tablebases work properly now, and I don't care much about playing without them (aside from tests) tablebase code will always be included from now.
=> Removed USE_TBS

src/cli.c, src/tests.c
Couple small changes to cli/matetest
=> Improve matetest/cli

src/bitboards.h, src/move.c, src/move.h, src/movegen.c
Added a function to check whether a move is psuedo-legal. Will be used to test the move found in TT, if it is psuedo-legal then we can try it before doing move generation, hopefully saving a lot of time.
=> Move is psuedo legal

src/move.c
=> Fix MoveIsPsuedoLegal

.editorconfig
Trying to get 4 space tabs in diff.
=> 4 space tabs

src/evaluate.c
Use whitePawns / blackPawns instead of recalculating.
=> CleanupKingSafety

src/move.c
Fixed pawn square logic being reversed relative to color.
=> Fix MoveIsPsuedoLegal2

src/movepicker.c, src/movepicker.h, src/search.c
=> Add init movepicker functions

src/search.c
Use the same LMR formula as Ethereal. May try the old one again when I can tune it to see if it can match this one.
ELO   | 20.28 +- 9.75 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2675 W: 811 L: 655 D: 1209
http://chess.grantnet.us/viewTest/3695/
ELO   | 36.85 +- 12.61 (95%)
Games | N: 1325 W: 370 L: 230 D: 725
http://chess.grantnet.us/viewTest/3696/
=> Ethereal LMR formula

src/search.c
Using recently added MAX/MIN macros more for readability, made some code more concise and removed some asserts and an old comment.
=> Cleanup search.c

src/search.c
Switched from tabs to 4 spaces and renamed some variables.
=> Cleanup search.c 2

src/evaluate.c
An incredibly basic and naive implementation of mobility scoring. Gives 1 centipawn for each psuedolegal move available to pieces except king and pawns. This is still a huge gain apparently.
ELO   | 45.30 +- 15.03 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1180 W: 411 L: 258 D: 511
http://chess.grantnet.us/viewTest/3705/
ELO   | 61.27 +- 17.69 (95%)
Games | N: 825 W: 297 L: 153 D: 375
http://chess.grantnet.us/viewTest/3707/
=> Basic mobility

src/evaluate.c
Not counting squares we would likely not want to move to (attacked by opposing pawns), squares we can't realistically open up for the piece (occupied by our blocked pawns), and squares occupied by our pawns in their starting positions. Can also be seen as not giving a bonus for defending these two types of pawns.
ELO   | 12.87 +- 7.85 (95%)
Games | N: 5025 W: 1770 L: 1584 D: 1671
http://chess.grantnet.us/viewTest/3721/
ELO   | 15.95 +- 8.73 (95%)
Games | N: 3705 W: 1213 L: 1043 D: 1449
http://chess.grantnet.us/viewTest/3722/
=> Restrict area used to count mobility

src/evaluate.c
=> Fix using wrong pawns

src/defs.h
Going forward, versions will be incremented after a release and appended -dev. On release the -dev is removed, before the next commit increments and adds -dev back.
=> Update version to 0.7-dev

src/evaluate.c, src/evaluate.h
Split evaluation of pieces into separate functions. This avoids a lot of code duplication, but is slightly slower due to having to generalize the functions.
=> Refactor eval

src/uci.c
Split setoption out into a separate function, added feedback for tablebase init, and cleaned up a bit.
=> Uci feedback

src/attack.c, src/bitboards.c, src/bitboards.h, src/board.c, src/board.h, src/evaluate.c, src/hashkeys.c, src/movegen.c, src/psqt.c, src/search.c, src/transposition.c, src/types.h, src/uci.c
Adding always_inline def for the ability to mimic C++ templates. Also added a def for constructors to clean up the code slightly.
=> Defs for inline/constructor

src/search.c
Futility pruning prunes moves that seem too bad before making them in the move loop by comparing static eval + some estimate of the gain of the move to alpha with some margin. The implemented reverse futility pruning instead makes the move first, then compares the static eval, which at that point includes the exact gain of the move, to beta with some margin. It also prunes earlier than depth 1, aka extended futility pruning, increasing the margin for higher depths as the potential for gain before reaching depth 0 is higher.
For weiss the difference between the normal and reverse versions means being able to easily avoid pruning while in check - I don't have a way to check whether a move will give check before making it yet -, as well as removes the need to try to estimate the gain of the …
=> Futility Pruning

src/search.c
Also known as move count pruning, after trying some quiet moves we give up, assuming that the chance for one of the remaining quiet moves to be better than what we've found so far is sufficiently low. The numbers/formula are probably far from optimal.
ELO   | 20.17 +- 9.85 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2914 W: 971 L: 802 D: 1141
http://chess.grantnet.us/viewTest/3916/
ELO   | 24.67 +- 10.57 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2187 W: 652 L: 497 D: 1038
http://chess.grantnet.us/viewTest/3917/
=> Late Move Pruning

src/defs.h
=> Version 0.7

src/defs.h, src/makefile, src/uci.c
Added a target to the makefile that makes nopopcnt, popcnt, and pext compiles. Changed author to my real name, and updated version to 0.8-dev.
=> Makefile release target

src/defs.h, src/search.c, src/transposition.c, src/transposition.h, src/types.h
These have gone unused for too long, and with the ability to test changes in self-play games I don't feel like I need them anymore. If I do it will be easy to add back in, and in the meantime I'll enjoy cleaner code.
=> Remove search stats

src/search.c
Small, non-functional changes to search. Has little to no impact on speed.
http://chess.grantnet.us/viewTest/4046/
=> Cleanup search

src/search.c
By using the history to check for a null move, the doNull parameter of AlphaBeta is made redundant. The only functional change is that null move can now be attempted immediately in internal iterative deepening, but this doesn't seem to make much of a difference.
ELO   | 2.66 +- 4.63 (95%)
Games | N: 13200 W: 4089 L: 3988 D: 5123
http://chess.grantnet.us/viewTest/4319/
=> Cleaner NMP condition

src/evaluate.c, src/evaluate.h
Cleaned up, no functional change. 
ELO   | 0.09 +- 3.50 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=32MB
LLR   | 1.05 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 24384 W: 7869 L: 7863 D: 8652
http://chess.grantnet.us/viewTest/4343/
=> Cleanup evalinfo initialization

src/attack.c, src/bitboards.c, src/bitboards.h, src/board.c, src/board.h, src/cli.c, src/evaluate.c, src/hashkeys.c, src/makemove.c, src/move.c, src/movegen.c, src/search.c, src/search.h, src/syzygy.h, src/tests.c, src/tests.h, src/transposition.c, src/types.h, src/uci.c
Naming cleanup, uses new helper functions in older code where it makes sense, and removes an unused lookup table.
=> Various Trivial Cleanups 2

src/types.h, src/uci.c
Improves readability of uci.c.
ELO   | -0.10 +- 2.88 (95%)
LLR   | 1.16 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 33806 W: 10250 L: 10260 D: 13296
http://chess.grantnet.us/viewTest/4471/
=> Cleanup uci.c

src/movegen.c
Small trivial changes.
ELO   | -0.21 +- 3.61 (95%)
LLR   | 0.63 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 21446 W: 6485 L: 6498 D: 8463
=> Cleanup movegen

src/attack.c
Renames and reorders some stuff, and a good readability improvement for InitSliderAttacks.
For some reason the virtual machine workers love this patch (~9 elo increase) while the other workers go more or less even. Not sure why.
http://chess.grantnet.us/viewTest/4584/
http://chess.grantnet.us/viewTest/4586/
http://chess.grantnet.us/viewTest/4587/
=> Cleanup attack.c

src/attack.c, src/evaluate.c, src/makemove.c, src/movegen.c, src/search.c, src/types.h
Adds a macro for bitboards of colored pieces for prettier code.
=> ColorPieceBB macro

src/search.c, src/uci.c
Small cleanups, possible speedup in search.
http://chess.grantnet.us/viewTest/4680/
=> Trivial cleanup

src/search.c
Reduce depth when resolving fail highs, lower beta when resolving fail lows, and reduce the rate at which the aspiration window grows.
ELO   | 6.78 +- 4.87 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10352 W: 2850 L: 2648 D: 4854
http://chess.grantnet.us/viewTest/4735/
ELO   | 8.19 +- 5.31 (95%)
LLR   | 3.11 (-2.94, 2.94) [0.00, 5.00]
Games | N: 7638 W: 1867 L: 1687 D: 4084
http://chess.grantnet.us/viewTest/4737/
=> Tweak aspiration

src/evaluate.c
Consolidate the eval functions for knight, bishop, rook and queen into a single function. King and pawn eval will end up quite large so they are kept separate. This should result in very similar assembly due to inlining, while avoiding a fair bit of repeated code.
http://chess.grantnet.us/viewTest/4769/
Score of weiss dev vs weiss master: 1075 - 1029 - 1896 [0.506]
Elo difference: 4.00 +/- 7.80
=> Combine eval functions for NBRQ

src/movegen.c
=> Fix compiler warning

src/search.c
Fix eval in root always being NOSCORE, preventing improving from being true at ply 2 in all cases.
ELO   | 1.96 +- 2.53 (95%)
LLR   | 0.08 (-2.94, 2.94) [0.00, 5.00]
Games | N: 37488 W: 9840 L: 9629 D: 18019
http://chess.grantnet.us/viewTest/4817/
=> Fix eval in root

src/search.c, src/types.h
Last patch was kind of a mess.
ELO   | 1.91 +- 3.96 (95%)
Games | N: 15822 W: 4295 L: 4208 D: 7319
http://chess.grantnet.us/viewTest/4821/
=> Cleanup of last patch

src/search.c, src/types.h, src/uci.c
Fix depth-limited search waiting for stop.
=> Bugfix previous commit

src/search.c
Fix a bug which made weiss use the TB result, even if it was worse than the current score. This had little to no impact on strength as it probably only made weiss pick worse, but still winning lines in the end game.
Also made weiss use TB score as new alpha when applicable which speeds up some end game test positions. Inspired by SF.
patch vs master: 585 - 584 - 1264 [0.500]
Elo difference: 0.14 +/- 9.56
=> Bugfix for tablebases

src/bitboard.c, src/bitboard.h
Using LandingSquareBB() to simplify MakeSliderAttackBB().
Inspired by @protonspring
=> Cleanup bitboards.c

src/search.c
Might make a return at some point, but for now I'll keep it simple.
ELO   | 5.28 +- 4.09 (95%)
Games | N: 14144 W: 3718 L: 3503 D: 6923
http://chess.grantnet.us/test/5058/
ELO   | 9.08 +- 5.70 (95%)
Games | N: 6240 W: 1449 L: 1286 D: 3505
http://chess.grantnet.us/test/5062/
=> Retire dynamic aspiration

src/uci.c
Refactor long clunky lines using a helper function.
=> Cleanup TC parsing

src/uci.c
Since version 0.9 a little over 2 months ago Weiss has gained about 250 self-play elo.
ELO   | 250.69 +- 6.77 (95%)
Games | N: 10708 W: 7473 L: 857 D: 2378
http://chess.grantnet.us/test/5376/
=> Weiss 0.10

src/fathom/tbprobe.c, src/fathom/tbprobe.h, src/syzygy.h
=> Cleanup syzygy

src/bitboard.c, src/board.c, src/board.h, src/evaluate.c, src/evaluate.h, src/search.c
Fixes compilation for clang and change some structures to remove -fsanitize errors. Also removes undefined behavior.
Non-functional change.
=> Miscellaneous fixes

src/move.c, src/move.h
Fixed a lot of special cases I didn't think of originally, and the original testing didn't show.
Hopefully fixes #226 
ELO   | 0.56 +- 2.74 (95%)
LLR   | 3.03 (-2.94, 2.94) [-4.00, 0.00]
Games | N: 29728 W: 7211 L: 7163 D: 15354
http://chess.grantnet.us/test/5440/
=> Fix bugs in pseudo legality test

src/board.c, src/move.c
I mistakenly &ed a bitboard and a square number in the en passant test. Fixed that as well as printboard printing random characters following the ep square.
=> Bugfix cleanup

src/move.c, src/move.h
Slight refactoring.
http://chess.grantnet.us/test/5492/
=> Cleanup MoveIsPseudoLegal

src/tests.c, src/tests.h, src/uci.c
Can now run bench with more than 1 thread: ./weiss bench <depth> <threadcount>
=> Add threads option to bench

src/uci.c
=> Cleanup SMP

src/search.c, src/threads.c, src/threads.h, src/transposition.c, src/types.h, src/uci.c, src/uci.h
Make sure to wait for stop in an infinite search. Also sleep instead of busy-waiting in a loop to not waste cpu power when reaching max depth in an infinite search.
Refactor a some of the UCI loop / functions.
=> Cleanup SMP 2

README.md, src/board.c, src/board.h, src/makefile, src/noobprobe/noobprobe.c, src/noobprobe/noobprobe.h, src/search.c, src/uci.c
Weiss can now probe noobpwnftw's online opening database and play the moves suggested by it.
No regression without use:
ELO   | 1.44 +- 3.38 (95%)
LLR   | 2.96 (-2.94, 2.94) [-4.00, 0.00]
Games | N: 20256 W: 5123 L: 5039 D: 10094
http://chess.grantnet.us/test/5639/
A bit stronger using it:
ELO   | 5.55 +- 5.17 (95%)
LLR   | 2.98 (-2.94, 2.94) [-2.50, 2.50]
Games | N: 8632 W: 2220 L: 2082 D: 4330
http://chess.grantnet.us/test/5640/
=> Support probing Chess Cloud Database

src/search.c, src/search.h, src/uci.c
=> Tiny cleanup

src/noobprobe/noobprobe.c, src/noobprobe/noobprobe.h, src/search.c, src/uci.c
After probing fails 3 consecutive turns give up probing for the rest of the game.
=> NoobBook: Stop probing after leaving book

src/tests.c
Inspired by Ethereal, collect results of each search and present them at the end.
=> Improve bench output

.github/workflows/make.yml
Adding a pipeline demonstrates to other developers how to test and release your program with results displaying in https://github.com/TerjeKir/weiss/actions .  Hopefully I guessed correctly. :-)
Congratulations on your 1.0 release!
=> Add CI pipeline

src/board.c, src/makemove.c, src/search.c, src/types.h, src/uci.c
=> Fix move counter in printed FEN

src/time.c
ELO   | 12.58 +- 6.28 (95%)
SPRT  | 40/40.0s Threads=1 Hash=32MB
Games | N: 5056 W: 1181 L: 998 D: 2877
http://chess.grantnet.us/test/6190/
=> Spend time slower (cyclic) 2

src/time.c, src/uci.c
=> Cleanup time management

src/evaluate.c
=> Update comments in eval

src/board.h, src/evaluate.h, src/makemove.h, src/movegen.c, src/movegen.h, src/movepicker.c, src/movepicker.h, src/noobprobe/noobprobe.c, src/noobprobe/noobprobe.h, src/search.c, src/search.h, src/threads.c, src/threads.h, src/time.h, src/transposition.h, src/types.h
Moved most structs from types.h to the relevant headers.
=> Cleanup types.h

src/evaluate.c
=> Small cleanup

src/tuner/tuner.c, src/tuner/tuner.h, src/uci.h
=> Small QoL improvements to tuner

src/search.c
Remove one redundant condition from nmp, and put each condition on a separate line for all the pruning heuristics.
=> Cleanup search a bit

src/movepicker.c
Simplified some of the new SEE-related code.
=> Cleanup movepicker

src/search.c
do not check for 50-move or rep. draw in QS
=> QS_noDrawCheck

src/search.c
Move some code from AB into a new helper function.
=> Refactor hist updates

src/movepicker.c, src/movepicker.h, src/search.c
=> Cleanup movepicker list

src/bitboard.c, src/bitboard.h, src/board.c, src/board.h, src/makemove.c, src/move.c, src/search.c, src/search.h, src/syzygy.h, src/threads.h, src/types.h, src/uci.c, src/uci.h
Use a search stack to keep track of various data relevant at each individual search depth. Makes it easy to look up data from previous depths.
Idea from Stockfish
=> Search stack

src/noobprobe/noobprobe.c, src/noobprobe/noobprobe.h, src/search.c, src/search.h, src/uci.c
Add an option to limit NoobBook to the first x moves of a game.
No functional change if not using NoobBook
=> Add option to limit NoobBook to x moves

src/board.c, src/pyrrhic/tbprobe.c, src/syzygy.h, src/tests.c, src/transposition.c, src/uci.c
Set stdout to line buffered instead of doing fflush() explicitly.
=> Use line buffered stdout

src/evaluate.c
Count piece as participating in the attack if it can give check.
Passed tests:
ELO   | 9.21 +- 5.90 (95%)
Games | N: 6336 W: 1596 L: 1428 D: 3312
ELO   | 7.24 +- 4.73 (95%)
Games | N: 7776 W: 1545 L: 1383 D: 4848
=> Generalized Checks in the attack

src/board.c, src/evaluate.c, src/evaluate.h, src/makemove.c
=> Index PhaseValue by piecetype instead of piece

src/bitboard.c, src/bitboard.h, src/evaluate.c, src/movegen.c
=> Cleanup pawn movegen

src/evaluate.c, src/search.c, src/tuner/tuner.c, src/tuner/tuner.h
=> Cleanup tuner

src/search.c, src/tests.c
Use time elapsed rather than just optimal time usage to decide when to prune, and reconsider between fail high/lows.
=> Tweak pruning

src/movepicker.c
Rather than look through the list for the best move each time we need a move, just presort it and return the next move in the list when needed.
ELO   | 6.89 +- 5.22 (95%)
Games | N: 8016 W: 1970 L: 1811 D: 4235
ELO   | 2.64 +- 2.62 (95%)
Games | N: 25712 W: 4991 L: 4796 D: 15925
=> Pre-sort movelist

src/search.c
ELO   | 1.92 +- 1.96 (95%)
LLR   | 3.03 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 56364 W: 13369 L: 13057 D: 29938
ELO   | 1.55 +- 1.87 (95%)
LLR   | 2.15 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 49832 W: 9459 L: 9236 D: 31137
=> Tweak QS futility margin

src/evaluate.c, src/tuner/tuner.c, src/tuner/tuner.h
These terms aren't helping anymore.
ELO   | 0.18 +- 2.07 (95%)
LLR   | 3.02 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 40784 W: 7750 L: 7729 D: 25305
=> Simplify queen open file

src/search.c
STC test result only, LTCs done vs other values but not master.
ELO   | 16.26 +- 8.37 (95%)
Games | N: 3080 W: 789 L: 645 D: 1646
=> Tune static exchange evaluation pruning

src/time.c
ELO   | 2.57 +- 4.61 (95%)
LLR   | 3.01 (-2.94, 2.94) [-5.00, 1.00]
Games | N: 9868 W: 2277 L: 2204 D: 5387
=> Simplify time management

src/search.c
Delta pruning is no longer useful, likely its intended effect is better achieved by the per-move futility prunings.
ELO   | 1.87 +- 3.51 (95%)
LLR   | 2.99 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 15952 W: 3438 L: 3352 D: 9162
ELO   | 6.74 +- 5.26 (95%)
Games | N: 5720 W: 1035 L: 924 D: 3761
=> Remove delta pruning

src/evaluate.c
Move scale factor logic to a separate function, and don't let the 2 scale factors combine.
ELO   | 1.42 +- 3.21 (95%)
LLR   | 2.97 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 18784 W: 3961 L: 3884 D: 10939
=> Cleanup scale factor

src/tuner/tuner.c
=> Improve tuner piece value print

src/history.h, src/movepicker.c, src/uci.c
=> Cleanup history

src/movepicker.c
ELO   | 8.57 +- 5.60 (95%)
GAMES | N: 5920 W: 1259 L: 1113 D: 3548
ELO   | 3.11 +- 2.79 (95%)
GAMES | N: 17872 W: 2761 L: 2601 D: 12510
=> Auto good noisy margin down

README.md, src/makefile, src/onlinesyzygy/onlinesyzygy.c, src/onlinesyzygy/onlinesyzygy.h, src/syzygy.h, src/uci.c
Adds UCI option allowing weiss to query lichess' online 7-men tablebases.
Closes #497
=> Online syzygy

src/search.c, src/threads.h, src/uci.c, src/uci.h
Print all multi-pv lines at the same time for better compatibility with Nibbler GUI.
=> Multi pv print fix

src/search.c, src/threads.c, src/threads.h
Print the different pvs ordered by score.
=> Multi-pv sort

src/search.c
Razor provides no value anymore.
=> Remove razoring

src/evaluate.c, src/tuner/tuner.c, src/tuner/tuner.h
Fix bug in tracing eval.
Verify evaluating the coeffs of all tuner entries matches real eval (within 1 cp).
Also simplify init of PSQT base params.
=> Verify tuner

src/makefile, src/noobprobe/noobprobe.c, src/noobprobe/noobprobe.h, src/onlinesyzygy/onlinesyzygy.c, src/query/query.c, src/query/query.h
Avoid repeating the query code.
=> Cleanup query code

src/move.c, src/move.h, src/movegen.c, src/syzygy.h
=> Reorder move encoding

src/onlinesyzygy/onlinesyzygy.c
Seems they changed the info they return on probing causing weiss to segfault.
=> Update to parse new response from lichess

src/query/query.c
Not really possible, but static code review software can't tell.
=> Fix possible buffer overflow

src/search.c
=> Avoid reducing root search depth below 1

src/search.c, src/tests.c, src/transposition.c, src/transposition.h, src/uci.c
=> Cleanup + fix max hash size

src/bitboard.h, src/board.c, src/board.h, src/evaluate.c, src/makemove.c, src/material.c, src/material.h, src/uci.c
We no longer have tablebases on our test machines at openbench, so properly evaluating endgames is valuable for training. Will have zero impact on real playing conditions.
=> Add specialized endgame evaluations

.gitignore, src/bitboard.c, src/board.c, src/board.h, src/material.c, src/material.h, src/psqt.c, src/search.c, src/types.h, src/uci.c
=> Add ordering to constructors to remove some init calls

src/search.c
Also move the max ply check before the inCheck skip.
=> Check for repetition and 50 move rule in qsearch

src/pyrrhic/tbprobe.c
Positions over DTZ 1000 could be wrong.
=> Update Pyrrhic to handle positions with very high DTZ

src/search.c
ELO   | 2.27 +- 2.35 (95%)
GAMES | N: 44160 W: 11791 L: 11503 D: 20866
ELO   | 5.88 +- 4.79 (95%)
GAMES | N: 9928 W: 2523 L: 2355 D: 5050
=> LMR more in cutnodes

src/search.c
=> Clean up LMR

src/Makefile, src/board.c, src/evaluate.c, src/makemove.c, src/material.c, src/onlinesyzygy/onlinesyzygy.c, src/pyrrhic/tbchess.c, src/pyrrhic/tbprobe.c, src/query/query.c, src/syzygy.h, src/tests.c
=> Add -Wmissing-declarations

src/board.c, src/board.h, src/move.c
=> Add SqToStr helper function

src/search.c
ELO   | 6.46 +- 5.16 (95%)
GAMES | N: 9144 W: 2493 L: 2323 D: 4328
ELO   | 16.38 +- 8.48 (95%)
GAMES | N: 3120 W: 829 L: 682 D: 1609
=> Probe TT in QSearch

src/search.c
=> Remove needless 0-initialization of 2 arrays

src/material.c
Triggers an assert when running with debug on.
=> Fix GenMaterialKey creating positions with king capturable

src/tuner/tuner.c
=> Add static to local tuner functions

src/search.c
Regression bounds:
ELO   | 0.38 +- 2.76 (95%)
GAMES | N: 31456 W: 8179 L: 8145 D: 15132
=> Avoid extending too far

.github/workflows/make.yml
=> Add perft to github actions

.github/workflows/make.yml
Ensure the correct amount of positions were tested.
Bench: 19785851
=> Improve perft github action

src/evaluate.c, src/tuner/tuner.c, src/tuner/tuner.h
ELO   | 3.47 +- 3.38 (95%)
GAMES | N: 21616 W: 5894 L: 5678 D: 10044
ELO   | 2.52 +- 2.60 (95%)
GAMES | N: 33880 W: 8535 L: 8289 D: 17056
=> Bonus for pawns sheltering the king

.github/workflows/make.yml, src/Makefile, src/types.h
=> Github Actions: Run bench with debug on

src/search.c
=> Fix ss->doubleExtensions not being initialized correctly

src/history.h
=> Add function for updating all continuation histories

src/movegen.c
=> Refactor GenPieceType a bit

src/search.c, src/transposition.h
=> Clean up search

src/move.c, src/move.h, src/movegen.c, src/movegen.h, src/search.c, src/syzygy.h, src/tests.c, src/threads.c, src/transposition.c, src/types.h
=> Clean up misc

src/search.c, src/search.h, src/threads.c, src/threads.h, src/types.h
=> Replace volatile variables with atomics

src/bitboard.c, src/bitboard.h, src/uci.c
=> Clean up bitboard.c/h

src/noobprobe/noobprobe.c
Some users reported issues with `http`.
=> switch to https for NoobBook

src/noobprobe/noobprobe.c
=> Add info print when NoobBook doesn't return a move to play

README.md, src/noobprobe/noobprobe.c, src/noobprobe/noobprobe.h, src/onlinesyzygy/onlinesyzygy.c, src/query/query.c, src/query/query.h, src/uci.c
Allows choosing between (poorly named) options 'best' and 'all'.
=> Add NoobBookMode option

src/uci.c
The option declaration was missing 'type'
=> Fix malformed UCI option NoobBookMode

src/Makefile
=> Change to -flto=auto

src/evaluate.c
=> Remove bugged code that has no effect on the result

src/history.h, src/search.c
=> Clean up correction history

src/history.h, src/threads.c, src/threads.h
=> Clean up correction history implementation

src/bitboard.c, src/bitboard.h
=> Clean up Magic BBs

.github/workflows/make.yml
=> Update to new version of checkout in github actions

src/transposition.c, src/transposition.h
=> Add EntryEmpty function for improved readability and reset generation on TT clear

src/search.c
Elo   | 1.97 +- 1.59 (95%)
Games | N: 69420 W: 18930 L: 18536 D: 31954
Penta | [1184, 8167, 15636, 8517, 1206]
http://chess.grantnet.us/test/38399/
Elo   | 5.01 +- 3.00 (95%)
Games | N: 15608 W: 3967 L: 3742 D: 7899
Penta | [119, 1761, 3832, 1960, 132]
http://chess.grantnet.us/test/38401/
Bench: 19917137
=> Scale down eval as 50mr approaches to incentivize being active when winning and passive when losing

src/search.c, src/types.h
=> Use newly added ss->move instead of history().move

src/history.h, src/threads.c, src/transposition.c
=> Clean up Continuation Correction History and some includes

src/search.c
Elo   | -0.78 +- 1.75 (95%)
LLR   | 2.96 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 57984 W: 15839 L: 15970 D: 26175
Penta | [1108, 6853, 13079, 6966, 986]
http://chess.grantnet.us/test/38539/
Elo   | 0.33 +- 2.45 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 22846 W: 5714 L: 5692 D: 11440
Penta | [165, 2725, 5614, 2761, 158]
http://chess.grantnet.us/test/38540/
Bench: 26976542
=> Refactor so every call to qsearch is the same, whether from main search or qsearch itself

src/history.h
=> Add asserts to HistoryBonus()

src/history.h, src/movepicker.c, src/search.c
STC 25k vs master
Elo   | 6.98 +- 3.85 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 12740 W: 3796 L: 3540 D: 5404
Penta | [249, 1440, 2771, 1626, 284]
http://chess.grantnet.us/test/38736/
LTC 5k vs master
Elo   | 4.27 +- 2.70 (95%)
Games | N: 18734 W: 5036 L: 4806 D: 8892
Penta | [120, 2150, 4618, 2338, 141]
http://chess.grantnet.us/test/38704/
LTC 15k vs 5k
Elo   | 5.53 +- 3.18 (95%)
Games | N: 13938 W: 3702 L: 3480 D: 6756
Penta | [92, 1621, 3338, 1809, 109]
http://chess.grantnet.us/test/38720/
LTC 25k vs 15k
Elo   | 1.50 +- 1.21 (95%)
LLR …
=> SPSA tune search and history
