TerjeKir/weiss

src/hashkeys.c
src/tests.c
src/transposition.c

As rand() works differently on different platforms, bench results varied between linux and windows in some cases. Using the psuedo-RNG from Ethereal, at least for now, fixes the problem.
Also a couple of minor improvements:
- Cleanup bench, also might avoid errors when the bench completes too fast.
- Avoid checking table size, which at that point is uninitialized, the first time TT is initialized.

Platform-independent RNG

---

src/search.c

Tiny speedup of IsRepetition by incrementing by 2 and traversing positions backwards from the end:
- A position with the same hash but the other side to move (every other position) should in a perfect world never happen, but even if it did, it wouldn't signify a repetition.
- Short repetitions near the end of a PV are probably more common than long cycles of shuffling, so looking at the most recent positions first will be slightly faster, slightly more often. When there is no repetition this shouldn't affect performance at all.
Test should have used lower bounds like -4, 0:
ELO   | 1.20 +- 3.33 (95%)
LLR   | -0.40 (-2.94, 2.94) [-1.50, 4.50]
Games | N: 31250 W: 11743 L: 11635 D: 7872

Check only for same turn to move

---

src/search.c
src/syzygy.c
src/syzygy.h

Removed so far unused TB_PROBE_DEPTH, I'll assume TBs are not saved on a slow medium (HDD). Cleaned up code a little and added comments. There should be no functional change.

Cleaned up + commented syzygy

---

src/movegen.c
src/movegen.h
src/search.c
src/tests.c
src/transposition.c
src/transposition.h
src/types.h

Collecting PV on the stack rather than getting it from the TT. PV now makes sense in 3-fold repetition scenarios, and is not cut short by TT overwrites.
Due to immediately returning the result of a TT hit even in PV-nodes, there would be no pv collected whenever the pv had already been explored and stored in the TT. To make sure a pv is always collected a TT hit in a PV-node no longer immediately returns, unless it's a frontier node. This change was unexpectedly also a big improvement to playing strength as well.
ELO   | 45.87 +- 15.29 (95%)
LLR   | 2.98 (-2.94, 2.94) [-5.00, -1.00]
Games | N: 1440 W: 607 L: 418 D: 415
http://chess.grantnet.us/viewTest/3576/

Pv list on the stack

---

src/types.h

Increase NB in mg to discourage early 2 N/B for R+P trades, scale up PQR in eg relative to NB as they tend to be stronger in the endgame.
ELO   | 7.54 +- 5.53 (95%)
Games | N: 10600 W: 3822 L: 3592 D: 3186
http://chess.grantnet.us/viewTest/3590/

TunePieceValues

---

src/evaluate.c

Lines from king not blocked by own pawns give a malus.
ELO   | 11.29 +- 7.31 (95%)
Games | N: 6250 W: 2353 L: 2150 D: 1747
http://chess.grantnet.us/viewTest/3596/

SimpleKingSafety

---

src/move.c
src/move.h
src/movepicker.c
src/movepicker.h
src/search.c

Implemented a movepicker so the move from TT can be tried before generating any moves, and all noisy moves tried before quiet moves are generated. Has a small impact on move ordering. Increases nps by a fair bit.
Might want to try killer moves before generating the other quiets.
ELO   | 8.48 +- 6.00 (95%)
Games | N: 8730 W: 3068 L: 2855 D: 2807
http://chess.grantnet.us/viewTest/3609/

MovePicker

---

src/makefile

OpenBench client now supports specifying target, but the old targets don't work as they save to a different folder.

OpenBench-compatible pext/pgo targets

---

src/makefile
src/move.h
src/search.c
src/uci.c

A pretty simple implementation of LMR with a static 1 ply reduction. Reduces the search tree a lot; depth 8 bench node count is reduced to ~1/7. Increased default depth of bench to 10, and pgo bench depth to 8 to compensate.
ELO   | 45.10 +- 15.76 (95%)
Games | N: 1255 W: 495 L: 333 D: 427
http://chess.grantnet.us/viewTest/3665/
ELO   | 63.96 +- 18.78 (95%)
Games | N: 835 W: 333 L: 181 D: 321
http://chess.grantnet.us/viewTest/3666/

Late Move Reduction

---

src/search.c

Start LMR 1 move later in pv nodes. Also increment movesTried earlier to match sf/ethereal.
ELO   | 3.78 +- 2.98 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 5.00]
Games | N: 30975 W: 9384 L: 9047 D: 12544
http://chess.grantnet.us/viewTest/3676/
ELO   | 3.82 +- 3.08 (95%)
Games | N: 26265 W: 7203 L: 6914 D: 12148
http://chess.grantnet.us/viewTest/3678/

LMR later in pv nodes

---

src/board.c
src/board.h
src/evaluate.c
src/makemove.c
src/types.h

Rather than recalculate the phase each call to evaluate() keeping it saved and updating it whenever the number of pieces changes. No functional change.
ELO   | 1.95 +- 4.63 (95%)
LLR   | 3.02 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 12860 W: 3870 L: 3798 D: 5192
http://chess.grantnet.us/viewTest/3686/

Incrementally update phase

---

src/makefile
src/search.c
src/types.h

Allow LMR to reduce depth by more than 1. Reduction increases with higher depth and the more moves have already been tried. 
ELO   | 48.44 +- 15.81 (95%)
LLR   | 3.08 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1155 W: 433 L: 273 D: 449
http://chess.grantnet.us/viewTest/3688/
ELO   | 21.32 +- 9.76 (95%)
Games | N: 2545 W: 743 L: 587 D: 1215
http://chess.grantnet.us/viewTest/3689/

Aggressive lmr

---

src/makefile
src/uci.c

Aggressive LMR reduced node count a lot yet again, so increasing default bench depths to compensate. No functional change.

Bench depth 13, pgo 12

---

src/search.c

Reduce a bit less with LMR.
ELO   | 7.21 +- 5.04 (95%)
Games | N: 9065 W: 2352 L: 2164 D: 4549
http://chess.grantnet.us/viewTest/3692/
ELO   | 10.16 +- 6.14 (95%)
Games | N: 5505 W: 1316 L: 1155 D: 3034
http://chess.grantnet.us/viewTest/3694/

Less aggressive LMR

---

src/evaluate.c

Makes mobility more important by giving more than 1 cp per move. Especially when a piece is on either extreme end of it's potential mobility. The values are probably higher than they should be, causing weiss to sacrifice material to gain mobility too much. Makes for a much more aggressive playstyle.
ELO   | 42.90 +- 15.54 (95%)
Games | N: 1400 W: 587 L: 415 D: 398
http://chess.grantnet.us/viewTest/3715/
ELO   | 53.75 +- 17.40 (95%)
Games | N: 1075 W: 450 L: 285 D: 340
http://chess.grantnet.us/viewTest/3719/

Mobility scores

---

src/search.c

Never drop into quiescence while in check. Should help discover mating lines and forks on the king.
ELO   | 18.14 +- 9.29 (95%)
Games | N: 3125 W: 989 L: 826 D: 1310
http://chess.grantnet.us/viewTest/3736/
ELO   | 23.61 +- 10.42 (95%)
Games | N: 2240 W: 662 L: 510 D: 1068
http://chess.grantnet.us/viewTest/3738/

Check extension before quiescence

---

src/search.c

Low base delta margin, increased by the best possible capture we could make (most valuable piece opponent has) and further increased if we have a pawn on the 7th as we might have a move that both promotes and captures.
ELO   | 8.38 +- 5.73 (95%)
Games | N: 7925 W: 2323 L: 2132 D: 3470
http://chess.grantnet.us/viewTest/3745/
ELO   | 8.82 +- 5.80 (95%)
Games | N: 6975 W: 1858 L: 1681 D: 3436
http://chess.grantnet.us/viewTest/3746/

Dynamic delta margin

---

src/search.c
src/types.h
src/uci.c

Using setbuf/longjmp to abort a search if time is up or a stop command is given. Moved more information into the SearchInfo struct to avoid warnings of clobbering. Hopefully this will help eliminate the time losses during testing.
Fixed a bug: The current PV in a new iteration of ID was used to print bestmove and pondermove, so if a search was aborted midway after changing the PV the new one would be printed despite the search not having finished proving it better.
Also cleaned up PrintThinking, AspirationWindow and SearchPosition a bit.
No functional changes.

Abort with long jmp

---

src/search.c

After the recent improvements, the score difference from one search iteration to the next is probably smaller, allowing a tightening of the aspiration window, increasing pruning, without incurring too many researches.
ELO   | 7.01 +- 5.02 (95%)
LLR   | 3.08 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10410 W: 3054 L: 2844 D: 4512
http://chess.grantnet.us/viewTest/3754/
ELO   | 9.34 +- 5.96 (95%)
Games | N: 6510 W: 1713 L: 1538 D: 3259
http://chess.grantnet.us/viewTest/3755/

Lower aspiration bonus

---

src/board.c
src/evaluate.c
src/makemove.c
src/types.h

Move the rest of the phase calculation out to makemove. Probably a speedup, passed -3, 1 SPRT on 5+0.05 and 10+0.1.
ELO   | 1.10 +- 2.89 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=32MB
Games | N: 32920 W: 9835 L: 9731 D: 13354
http://chess.grantnet.us/viewTest/3765/
ELO   | 2.28 +- 3.56 (95%)
LLR   | 3.04 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 20765 W: 5972 L: 5836 D: 8957
http://chess.grantnet.us/viewTest/3764/

Final phase value updated incrementally

---

src/move.h
src/movegen.c

Finally found a way to fix the horrible movegen code. The new setup takes advantage of forcing inlining so the compiler optimizes the code in a similar way to C++ templates. Saves almost 400 lines of code, making it far more readable, at no cost.
142 additions and 517 deletions.
<add test result>

Template movegen

---

src/evaluate.c

CLOP tuning of Bishop Pair and KLVuln values showed they were too small. My initial theory is that mobility evaluation may be a bit too high, or at least the other bonuses are too small relative to mobility. Preliminary results of a CLOP run on the remaining various bonuses/maluses, except passed pawns, show they should all be increased as well. This will be tested next. 
There seems to be a lot of ELO to be gained by improving evaluation values.
ELO   | 16.10 +- 8.74 (95%)
Games | N: 3650 W: 1181 L: 1012 D: 1457
http://chess.grantnet.us/viewTest/3850/
ELO   | 12.24 +- 7.21 (95%)
Games | N: 4854 W: 1406 L: 1235 D: 2213 …

Tune Eval 1

---

src/evaluate.c

CLOP tuning of various evaluation terms. CLOP indicated higher values in this and the previous tune #95 , but test games showed that more conservative increases performed better in both cases. Next up is tuning passed pawn values.
https://www.remi-coulom.fr/CLOP/
ELO   | 6.93 +- 5.12 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10329 W: 3121 L: 2915 D: 4293
http://chess.grantnet.us/viewTest/3868/
ELO   | 8.92 +- 5.89 (95%)
Games | N: 6931 W: 1892 L: 1714 D: 3325
http://chess.grantnet.us/viewTest/3872/

Tune eval 2

---

src/board.c
src/makemove.c
src/types.h

Keeping track of the piecelist index of the piece on each square. No longer has to loop through the piecelist to find the correct one. A very significant speed up; 8-10% faster bench on my machine, and test games show a clear improvement.
ELO   | 8.47 +- 5.76 (95%)
Games | N: 7919 W: 2345 L: 2152 D: 3422
http://chess.grantnet.us/viewTest/3874/

Piecelist Index

---

src/board.c
src/cli.c
src/evaluate.c
src/makemove.c
src/search.c
src/types.h

Simplification removing kingSq and using the piece list instead. Saves a few lines of codes, and speeds up makemove.
ELO   | 5.19 +- 5.06 (95%)
Games | N: 10441 W: 3095 L: 2939 D: 4407
http://chess.grantnet.us/viewTest/3875/

Remove pos->kingSq

---

src/movegen.c

Moved underpromotions to the quiet movegen which avoids generating them in quiescence search, as well as in the first stage (noisy) of normal search. As underpromotions beating queen promotions is extremely rare, this saves time at a very low cost to search quality. Probably also helps prepare removing promotions from the searchHistory heuristic.
ELO   | 5.20 +- 4.07 (95%)
Games | N: 15767 W: 4577 L: 4341 D: 6849
http://chess.grantnet.us/viewTest/3876/
<insert test result>
http://chess.grantnet.us/viewTest/3877/

No underpromotion in noisy movegen

---

src/movegen.c
src/search.c

Promoting captures were already excluded, now normal promotions too are also excluded from searchHistory. Pawns wanting to promote to a square does not necessarily imply that the square is good for other pieces to go to - it's not like the pawn has many options. This leads to slightly better move ordering and thus faster searches.
ELO   | 7.85 +- 5.52 (95%)
Games | N: 8630 W: 2545 L: 2350 D: 3735
http://chess.grantnet.us/viewTest/3879/
insert LTC

Remove promos from search history

---

src/movegen.c
src/search.c
src/types.h

If the same quiet move caused a beta cutoff twice in a row, both killers would become that move. This obviously isn't useful, and fixing it improves move ordering a fair bit. Also switched the indexing so elements used together are stored close together.
ELO   | 15.20 +- 8.49 (95%)
LLR   | 2.89 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3750 W: 1175 L: 1011 D: 1564
http://chess.grantnet.us/viewTest/3942/

No double killers

---

src/search.c

Update history also on a beta cutoff. The beta cutoffs are the best moves found in the position, so encouraging trying them earlier is obviously better than only encouraging moves that beat alpha but not beta.
Passes easily:
ELO   | 26.13 +- 11.31 (95%)
Games | N: 2105 W: 688 L: 530 D: 887
http://chess.grantnet.us/viewTest/3944/
And is probably slightly better than only updating on beta cutoffs:
ELO   | -2.90 +- 4.76 (95%)
LLR   | -3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10194 W: 2501 L: 2586 D: 5107
http://chess.grantnet.us/viewTest/3946/

Quiet history on beta cutoff

---

src/evaluate.c
src/search.c
src/types.h

Increased all eval scores by ~28% (aiming for 128 for pawn mg) to have a finer grain. I forgot to increase PSQTs at first, but local testing showed this to be a gain at STC so I went with it. Seems to be a wash at LTC, but this is the direction I want to go so I'll risk the slight regression - tuning values should bring it all back anyway.
ELO   | 4.61 +- 3.65 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 20349 W: 6083 L: 5813 D: 8453
http://chess.grantnet.us/viewTest/3984/
ELO   | 0.27 +- 2.83 (95%)
LLR   | -3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 29700 W: 7656 L: 7633 D: 14411
http://chess.grantnet.us/viewTest/3985/

Increased eval scores

---

src/types.h

Either weiss is better with bishops or knights are overvalued by other terms relative to bishops.
ELO   | 10.07 +- 6.51 (95%)
LLR   | 3.08 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6800 W: 2213 L: 2016 D: 2571
http://chess.grantnet.us/viewTest/4004/
ELO   | 9.70 +- 6.36 (95%)
SPRT  | 32.0+0.32s Threads=1 Hash=128MB
Games | N: 6625 W: 2007 L: 1822 D: 2796
http://chess.grantnet.us/viewTest/4005/

bishops > knights

---

src/search.c

Do a reduced-depth search when we don't get a move from the TT, then probe TT again to hopefully get one. Should improve move ordering, and skips movegen when the newly gained ttmove causes a cutoff. This version with MAX and MIN is a bit slow, so is not much of a gain at STC if at all, but is a decent gain at LTC. If I can get quiescence search to save to TT without losing elo, then the MAX can probably go.
ELO   | -0.00 +- 3.40 (95%)
LLR   | -2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 24451 W: 7480 L: 7480 D: 9491
http://chess.grantnet.us/viewTest/4038/
ELO   | 4.11 +- 3.24 (95%)
LLR   | 3.08 (-2.94, 2.94) [0.00, 5.00]
Games | N: 23155 W: 6217 L: 5943 D: 10995
http://chess.grantnet.us/viewTest/4040/

Internal Iterative Deepening

---

src/cli.c
src/search.c
src/tests.c
src/transposition.c
src/transposition.h
src/types.h
src/uci.c

Changed how TT probing is done so the variables are available in search for use in future heuristic. No functional change, and seemingly no noticable change in speed.
http://chess.grantnet.us/viewTest/4068/

Refactor TT probe/store

---

src/search.c

Devalue history at lower depths to a larger extent than before. This resulted in a much bigger gain than expected; I've tried this with short local tests earlier, but saw no improvement.
ELO   | 9.59 +- 6.40 (95%)
Games | N: 6850 W: 2167 L: 1978 D: 2705
http://chess.grantnet.us/viewTest/4083/
ELO   | 15.78 +- 8.33 (95%)
Games | N: 3525 W: 1009 L: 849 D: 1667
http://chess.grantnet.us/viewTest/4084/

Quadratic depth history bonus

---

src/search.c

Smaller initial aspiration window. Will have to try tweaking this even more as this was a much bigger gain than anticipated.
ELO   | 18.63 +- 9.53 (95%)
Games | N: 3174 W: 1069 L: 899 D: 1206
http://chess.grantnet.us/viewTest/4095/
ELO   | 15.49 +- 8.25 (95%)
Games | N: 3680 W: 1076 L: 912 D: 1692
http://chess.grantnet.us/viewTest/4097/

Smaller initial aspiration window

---

src/search.c

Another big gain from shrinking the aspiration window.
ELO   | 6.57 +- 4.96 (95%)
Games | N: 12331 W: 4161 L: 3928 D: 4242
http://chess.grantnet.us/viewTest/4099/
ELO   | 12.18 +- 7.24 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5109 W: 1565 L: 1386 D: 2158
http://chess.grantnet.us/viewTest/4101/

Lower dynamic aspiration bonus

---

src/search.c

Weirdly dividing by 128 does not improve from 64, but 256 does. I will probably redo the whole aspiration window function, in particular decoupling the initial window and the delta used to relax bounds upon failing high or low.
ELO   | 3.43 +- 2.64 (95%)
Games | N: 44551 W: 15166 L: 14726 D: 14659
http://chess.grantnet.us/viewTest/4108/
ELO   | 4.44 +- 3.54 (95%)
Games | N: 21622 W: 6456 L: 6180 D: 8986
http://chess.grantnet.us/viewTest/4110/

Lower aspiration window dynamic bonus

---

src/search.c

After increasing the evaluation terms absolute values by ~28% the reported score was inflated. This patch scales the reported score back down to be (approximately) centipawns. 
Tagged on a refactor of the aspiration window function. No functional change.

Scale printed score to be in centipawns

---

src/search.c

As expected the initial window of 8 was too small. Will continue tweaking aspiration.
ELO   | 11.30 +- 7.27 (95%)
Games | N: 5999 W: 2147 L: 1952 D: 1900
http://chess.grantnet.us/viewTest/4115/
ELO   | 8.52 +- 5.88 (95%)
Games | N: 7754 W: 2343 L: 2153 D: 3258
http://chess.grantnet.us/viewTest/4117/

Widen initial aspiration window

---

src/time.c

Previous patch broke linux time. This should fix it, as well as using a safer clock.

Fix time linux

---

src/search.c
src/search.h
src/tests.c
src/types.h
src/uci.c

Moved everything about time control and management except parsing the input from uci to search. 
Also increased time usage in increment time control which was a huge gain at least in self-play games.
ELO   | 34.01 +- 13.39 (95%)
Games | N: 1650 W: 602 L: 441 D: 607
http://chess.grantnet.us/viewTest/4200/
ELO   | 22.96 +- 10.22 (95%)
LLR   | 3.12 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2500 W: 784 L: 619 D: 1097
http://chess.grantnet.us/viewTest/4201/

Refactor time management

---

src/search.c

Rather than a static depth reduction of 4 on null move pruning searches, now uses 3 + depth / 4. Static reduction of 4 (or so) was supposedly common a long time ago when engines did much shallower searches, in recent times with vastly increased search depths it seems to be important to scale reductions with the depth.
ELO   | 6.92 +- 5.16 (95%)
Games | N: 11098 W: 3653 L: 3432 D: 4013
http://chess.grantnet.us/viewTest/4226/
http://chess.grantnet.us/viewTest/4228/

Dynamic NMP depth

---

src/search.c

Use null move pruning also at depth 3.
Tests vs depth 2 which beat 4 handily.
ELO   | 7.08 +- 5.15 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10695 W: 3381 L: 3163 D: 4151
http://chess.grantnet.us/viewTest/4231/
ELO   | 13.12 +- 7.49 (95%)
Games | N: 4426 W: 1270 L: 1103 D: 2053
http://chess.grantnet.us/viewTest/4235/

Null move prune at lower depth

---

src/search.c

Increase depth reduction based on how much eval beats beta. When static eval beats beta by a lot we don't need as strong evidence to conclude this is already too good.
ELO   | 5.36 +- 4.21 (95%)
Games | N: 15875 W: 4953 L: 4708 D: 6214
http://chess.grantnet.us/viewTest/4232/
ELO   | 11.48 +- 6.92 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5025 W: 1390 L: 1224 D: 2411
http://chess.grantnet.us/viewTest/4238/

Increase NMP depth reduction based on eval

---

src/search.c

Lowers the bonus to reduction given based on depth. Given the big elo gain it would seem likely that lowering it further is better still, or perhaps the eval bonus can increased.
ELO   | 7.79 +- 5.59 (95%)
Games | N: 9150 W: 2929 L: 2724 D: 3497
http://chess.grantnet.us/viewTest/4248/
ELO   | 7.76 +- 5.34 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 8549 W: 2348 L: 2157 D: 4044
http://chess.grantnet.us/viewTest/4249/

Lower NMP depth reduction

---

src/defs.h
src/transposition.c

Rather than always overwriting the old data in the transposition table, now only does so if the new data is for a different position, is the result of searching at least equally deep, or the data is an exact score (as opposed to being an upper or lower bound. An exact score is generally more useful when fetched again later).
ELO   | 16.98 +- 8.97 (95%)
Games | N: 3501 W: 1149 L: 978 D: 1374
http://chess.grantnet.us/viewTest/4267/
ELO   | 6.63 +- 4.79 (95%)
Games | N: 10434 W: 2803 L: 2604 D: 5027
http://chess.grantnet.us/viewTest/4268/

TT replacement scheme

---

src/makemove.c
src/search.c
src/types.h

Saves a history of static evaluations and uses them along with the move history to avoid recalculating the static evaluation after a null move; the position has obviously not changed aside from side to move so the evaluation is just the opposite of the previous.
ELO   | 8.63 +- 5.98 (95%)
Games | N: 7975 W: 2553 L: 2355 D: 3067
http://chess.grantnet.us/viewTest/4313/
ELO   | 7.87 +- 5.40 (95%)
Games | N: 8350 W: 2291 L: 2102 D: 3957
http://chess.grantnet.us/viewTest/4314/

Eval history

---

src/attack.c

General cleanup and refactoring of the way non-slider attack bitboards are initialized, based on code by protonspring for Stockfish. No functional change, the test result is likely just small sample size.
ELO   | 4.63 +- 5.68 (95%)
LLR   | 3.01 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 8925 W: 2841 L: 2722 D: 3362
http://chess.grantnet.us/viewTest/4339/

Cleanup attack bitboard initialization

---

src/makemove.c

Only rehash the castling rights if at least one side can castle, and either the to or from square is the original square of a king or rook.
ELO   | 5.59 +- 4.30 (95%)
LLR   | 3.06 (-2.94, 2.94) [0.00, 5.00]
Games | N: 15527 W: 4951 L: 4701 D: 5875
http://chess.grantnet.us/viewTest/4361/

Speedup MakeMove

---

src/search.c
src/time.c
src/time.h
src/types.h

Adds a minimum thinking time of 10ms, lowers move overhead to 30ms from 50, switches to using elapsed time rather than fixed points in time to check for timeout, and changes the OutOfTime logic to not check for timeout at 0 nodes as aborting a search at that point is nonsensical.
ELO   | 5.44 +- 4.25 (95%)
Games | N: 15765 W: 4969 L: 4722 D: 6074
http://chess.grantnet.us/viewTest/4359/
ELO   | 6.61 +- 5.74 (95%)
LLR   | 2.96 (-2.94, 2.94) [-2.50, 2.50]
Games | N: 7304 W: 1970 L: 1831 D: 3503
http://chess.grantnet.us/viewTest/4362/

Tweak time management

---

src/search.c
src/uci.c

No longer includes overhead in the time usage calculation of every turn, but rather only to keep a buffer of time. This results in using closer to all the time given at short TC, spending down to near 100ms left at 10+0.1 rather than ~500ms.
Also uses more time early on in repeating time controls rather than equal time on all turns, as saving a lot of time for later is pointless if the game is decided before it can be used. And saves at least 10ms for each move left (+ the overhead buffer).
ELO   | 18.49 +- 10.53 (95%)
Games | N: 2615 W: 886 L: 747 D: 982
http://chess.grantnet.us/viewTest/4374/
ELO   | 22.11 +- 10.66 (95%)
SPRT  | 40/9.0s Threads=1 Hash=32MB
Games | N: …

Improved time management

---

src/makefile

Avoid spamming the shell with search info during pgo makes.

Discard bench output during pgo

---

src/attack.c
src/bitboards.c
src/bitboards.h
src/evaluate.c
src/makemove.c
src/move.c
src/move.h
src/search.c
src/validate.c

CLRBIT is only called correctly (when the bit is 1) so flipping the bit by ^ with SetMask instead of &ing with ClearMask is safe. Saves the memory used by ClearMask, and speeds up makemove functions. SetMask renamed SquareBB.
move.h rewritten for improved readability, only real change is the order of the operations in the info extractor macros.
Cleaned up bitboards files and added an assert for lsb to check it isn't called with argument 0.
These seemingly tiny changes achieved an incredible performance in testing, though it could just be small sample size.
ELO   | 14.82 +- 8.20 (95%)
LLR   | 3.03 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 4200 W: 1367 L: 1188 D: 1645
http://chess.grantnet.us/viewTest/4391/

Speedup + Cleanup

---

src/move.c
src/move.h
src/movegen.c

Improved readability for MoveIsPseudoLegal (as well as castling movegen) by using a helper function for checking pseudo-legality of castling, new movetype macros, and cleaner sanity checks. 
ELO   | 1.73 +- 3.34 (95%)
LLR   | 3.00 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 25283 W: 7778 L: 7652 D: 9853
http://chess.grantnet.us/viewTest/4409/

Refactor MoveIsPseudoLegal

---

src/cli.c
src/search.c
src/tests.c
src/transposition.c
src/transposition.h
src/types.h
src/uci.c

Makes the TT global. Also avoids re-clearing it if it is already clear, which previously happened any time ucinewgame was given before the first game. Should be a speedup especially when using huge size TT.
ELO   | -0.96 +- 2.03 (95%)
LLR   | -0.36 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 68378 W: 20714 L: 20903 D: 26761
http://chess.grantnet.us/viewTest/4440/

Global transposition table

---

src/cli.c
src/transposition.c
src/transposition.h
src/uci.c

This change avoids allocating the TT with the default size only to free it and reallocate in the likely event that a hash size is specified by the user. This speeds up initialization in most cases.
If told to search before getting an 'isready' weiss will now crash. Checking for allocated TT on every 'go' showed a 4 elo loss so I will allow this behavior. With that said, the uci protocol specifies an isready must be given before starting a search to allow initialization to finish, and recommends it after any command which could take some time. Reasonable interpretation is that isready should always be given between setting hash size and starting a search.
```
* isready
this is used to synchronize the engine with the GUI. When the GUI has sent 
a command or multiple commands that can take …
```

Defer allocation of TT until necessary

---

src/makefile
src/transposition.c
src/transposition.h
src/uci.c

Aligns the transposition table with the cache line.
This seems to have fixed weiss' crashing - 93k games without crashing except on my machine which is likely a time control, or possibly windows, issue. Crashing on my machine is also greatly diminished compared to other recent tests.
ELO   | -0.16 +- 1.74 (95%)
Games | N: 93258 W: 28429 L: 28472 D: 36357
http://chess.grantnet.us/viewTest/4463/

Cache align TT

---

src/uci.c

Now correctly frees the memory allocated for the transposition table before exiting after benchmarking.

Free memory after benchmark

---

src/transposition.c
src/types.h
src/uci.c

On systems where size_t is not 64 bits, master produces warnings and prints nonsense sizes and entry counts for the transposition table. This patch fixes this by using %zu to print size_t on non-windows systems. On windows, MingW doesn't support %zu as it uses MSVCRT which conforms to C89 while the 'z' length modifier was added in C99.

Fix printing size_t on 32bit OS

---

src/search.c
src/transposition.c
src/transposition.h

No longer updates PV in quiescence search, the lines there are hardly reliable anyway so I'd rather have smaller/faster code. No longer updates seldepth in alpha-beta search as the quiescence search will amost always go deeper. Fixed ProbeTT using pos->posKey when it could have just used the posKey parameter. Faster logic in TB probe.

Cleanup search

---

src/search.c

Introduces the concept of improving - evaluation rising since our previous turn - and uses it to apply LMP more aggressively when we are not. Also moves the quiet count increment until after a move is proven legal, so only legal moves are counted.
ELO   | 7.20 +- 5.25 (95%)
Games | N: 10141 W: 3169 L: 2959 D: 4013
http://chess.grantnet.us/viewTest/4522/
ELO   | 9.77 +- 6.30 (95%)
Games | N: 6192 W: 1731 L: 1557 D: 2904
http://chess.grantnet.us/viewTest/4523/

Improved LMP

---

src/transposition.c
src/transposition.h

Inspired by SF, this patch introduces a faster TT index calculation formula. In SF this replaced a different fast method which has the drawback of limiting the hash size to powers of 2, and removing this limitation was the main pull. In weiss the modulo method already allowed any size hash, but is slow, and the speed increase is the reason for the change.
Also increases the max hash limit to 65536MB which is the limit the new formula can make use of given the 16B size entries used in Weiss.
ELO   | 3.89 +- 3.12 (95%)
Games | N: 28638 W: 8814 L: 8493 D: 11331
http://chess.grantnet.us/viewTest/4507/
ELO   | 2.60 +- 1.83 (95%)
Games | N: …

Faster TT index calculation

---

src/makemove.c
src/move.c

Xor'ing a square on rank 3 or 4 swaps it to the other one, and similarly for 5 and 6. Given the destination square of a pawn start we can calculate the en passant square this way. We can also calculate where the pawn we captured with an en passant move was. This is much cleaner, and faster, than the old method.
ELO   | 6.72 +- 6.02 (95%)
LLR   | 3.07 (-2.94, 2.94) [-2.50, 2.50]
Games | N: 8062 W: 2621 L: 2465 D: 2976
http://chess.grantnet.us/viewTest/4528/

Speedup en passant square calculation

---

src/board.c
src/board.h
src/search.c
src/transposition.c
src/transposition.h

Speculative prefetching of transposition table entry inspired by SF/CFish.
ELO   | 10.54 +- 7.17 (95%)
Games | N: 5575 W: 1810 L: 1641 D: 2124
http://chess.grantnet.us/viewTest/4534/
ELO   | 7.36 +- 5.79 (95%)
Games | N: 8450 W: 2677 L: 2498 D: 3275
http://chess.grantnet.us/viewTest/4535/

Prefetch TT entry

---

src/board.c
src/makemove.c

Resets the 50mr after null moves.
ELO   | 4.72 +- 4.89 (95%)
LLR   | 3.02 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 11788 W: 3675 L: 3515 D: 4598
http://chess.grantnet.us/viewTest/4545/

Reset 50mr on null move

---

src/attack.c
src/attack.h
src/bitboards.h
src/evaluate.c
src/fathom/tbconfig.h
src/move.c
src/movegen.c
src/types.h

Introduces new functions dealing primarily with pawn movement. Improves readability and apparently also speed.
ShiftBB is based on clever code by @protonspring .
ELO   | 7.28 +- 5.96 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 7925 W: 2490 L: 2324 D: 3111
http://chess.grantnet.us/viewTest/4559/

Cleaner pawn move code

---

src/attack.h

Use a macro for attack index calculation for prettier code. Doing the full calculation as one formula was also a speedup for non-pext builds apparently.
ELO   | 6.74 +- 5.73 (95%)
LLR   | 3.03 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 8711 W: 2772 L: 2603 D: 3336
http://chess.grantnet.us/viewTest/4577/

Cleanup attack.h

---

src/bitboards.c
src/board.c
src/evaluate.c
src/makemove.c

The main improvements are the cleaner ClearPosition, and the more intuitive phase calculation.
The slight loss will likely be fixed by future improvements to the size of the position struct, if it is indeed real.
ELO   | -2.78 +- 2.87 (95%)
LLR   | -2.97 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 34215 W: 10319 L: 10593 D: 13303
http://chess.grantnet.us/viewTest/4597/

Cleanup board.c

---

src/attack.c
src/board.c
src/makemove.c
src/transposition.h
src/types.h

Improve memory/cache usage with smaller ints.
ELO   | 3.92 +- 4.59 (95%)
Games | N: 13470 W: 4200 L: 4048 D: 5222
http://chess.grantnet.us/viewTest/4602/

Use smaller ints

---

src/attack.c
src/attack.h
src/bitboards.c
src/board.c
src/board.h
src/evaluate.c
src/makemove.c
src/makemove.h
src/move.c
src/move.h
src/movegen.c
src/movepicker.c
src/psqt.c
src/search.c
src/tests.c
src/transposition.c
src/transposition.h
src/types.h
src/uci.c
src/validate.c
src/validate.h

Adds typedefs for square and moves (uint32_t) for clearer code. Also fixes a bug from earlier today with the pext compile.
http://chess.grantnet.us/viewTest/4603/

Square and Move types

---

src/bitboards.h
src/board.c
src/evaluate.c
src/evaluate.h
src/makemove.c
src/search.c
src/types.h

The piecelist is an old relic inherited from VICE. Now with a full bitboard representation they add nothing in terms of functionality. In Stockfish they supposedly improve move ordering slightly, preventing their removal, but in Weiss they are not used for anything the bitboards can't do identically. Using them for movegen like in SF resulted in a regression, so there is no reason to keep them around.
Retires the piecelists, and refactors the code that relied on them. This results in a speedup.
ELO   | 6.05 +- 4.62 (95%)
Games | N: 13148 W: 4097 L: 3868 D: 5183
http://chess.grantnet.us/viewTest/4624/
Tests with no piecelists, but also no check material draw also showed a (smaller) gain: …

Retire piecelists

---

src/move.c

With the recent addition of the AttackBB function, most of the switch cases in moveIsPseudoLegal can be consolidated into one.
ELO   | -0.71 +- 2.91 (95%)
LLR   | 0.21 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 33563 W: 10304 L: 10373 D: 12886
http://chess.grantnet.us/viewTest/4617/

Refactor pseudo-legality test

---

src/search.c

Lower bar for pruning if our position is improving.
ELO   | 5.38 +- 4.23 (95%)
Games | N: 15748 W: 4907 L: 4663 D: 6178
http://chess.grantnet.us/viewTest/4667/
ELO   | 3.14 +- 2.45 (95%)
Games | N: 40480 W: 10784 L: 10418 D: 19278
http://chess.grantnet.us/viewTest/4675/

Improving reverse futility pruning

---

src/search.c

PVs have been broken ever since switching away from fetching them from the transposition table (which also sometimes broke them due to hash collision). This was caused by the aspiration window accepting scores on the edge of the window, hence not re-searching when it was supposed to.
This patch fixes the problem, but loses around 25 elo. Everything in the search is tuned to the old behavior, so hopefully as parameters are retuned the elo will be recovered.
ELO   | -25.14 +- 9.62 (95%)
LLR   | -2.95 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 2395 W: 485 L: 658 D: 1252
http://chess.grantnet.us/viewTest/4729/
ELO   | -27.63 +- 12.57 (95%)
LLR   | -2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1701 W: 423 L: 558 D: 720 …

Fix broken PVs

---

src/search.c

Allow LMR of captures, and tweak the reduction amount.
ELO   | 5.75 +- 4.38 (95%)
Games | N: 12813 W: 3508 L: 3296 D: 6009
http://chess.grantnet.us/viewTest/4750/
ELO   | 14.95 +- 7.72 (95%)
Games | N: 3487 W: 857 L: 707 D: 1923
http://chess.grantnet.us/viewTest/4751/

LMR captures

---

src/evaluate.c

Combine mobility bonuses into a single array indexed by piece type to make one generalized statement in EvalPiece(). Same for (semi-)open file bonuses for rook and queen.
This and the previous commit really highlight how simple the evaluation really is.
Score of weiss dev vs weiss master: 1048 - 1009 - 1960 [0.505]
Elo difference: 3.37 +/- 7.68

Combine eval functions for NBRQ part2

---

src/evaluate.c
src/evaluate.h
src/search.c
src/types.h

Per move futility pruning based on the piece being captured by each move. This is very similar to delta pruning, but instead of pruning all moves at once based on an approximated ceiling for improvement possible in the position, the per move version uses an approximation of the improvement of each move to try to prune them individually. Delta pruning is still useful as it completely skips movegen whenever it works.
ELO   | 33.79 +- 12.56 (95%)
Games | N: 1547 W: 480 L: 330 D: 737
http://chess.grantnet.us/viewTest/4777/
ELO   | 6.10 +- 4.43 (95%)
Games | N: 10710 W: 2523 L: 2335 D: 5852
http://chess.grantnet.us/viewTest/4778/

Per move futility pruning in queiscence search

---

src/search.c

Avoid pruning advanced pawn pushes in quiescence search.
ELO   | 8.15 +- 5.57 (95%)
Games | N: 7759 W: 2111 L: 1929 D: 3719
http://chess.grantnet.us/viewTest/4781/
ELO   | 5.36 +- 4.05 (95%)
Games | N: 12827 W: 3010 L: 2812 D: 7005
http://chess.grantnet.us/viewTest/4782/

No pruning advanced pawn pushes in QS

---

src/bitboards.h
src/board.c
src/evaluate.c
src/movegen.c

Add function to check if there are more than one set bits in a bitboard, simplify ParseFen, and split en passant and promotion generation into two functions as it makes no sense to combine them.

Trivial cleanup

---

src/transposition.c
src/transposition.h

Based on a recent patch for Ethereal by @skiminki , this patch aligns the transposition table to 2MB and requests the use of huge pages on linux. When huge pages are available and not used automatically this is potentially a big speedup. When huge pages are already used, the alignment will likely give a smaller speedup.
ELO   | 4.77 +- 4.73 (95%)
Games | N: 10936 W: 2966 L: 2816 D: 5154
http://chess.grantnet.us/viewTest/4790/

Request huge pages on linux

---

src/makemove.c
src/search.c
src/uci.c

During setup while parsing a 'position' command with more than 127 moves, pos->ply would temporarily go above the intended max value of 127 before being reset to 0 when starting the search. This didn't cause any problems, but triggered asserts in debug mode. Fixed by setting ply to 0 between each move instead of at the beginning of search.
Also fixed extending past MAXDEPTH when in check in root (in extremely simple positions, or positions where mate distance pruning took effect, where the search would reach MAXDEPTH). Also made iterative deepening stop before depth == MAXDEPTH as that seems to be the normal way to do it.

Fix unintended behavior

---

src/evaluate.c
src/search.c
src/syzygy.h
src/transposition.h
src/types.h

Changed up the score constants so they make more sense (mate in 0 is MATE, not INFINITE etc).
Also changed to not accept TB win scores from null move pruning as they represent number of moves to reach the TB win, and with a null move in the line that count is wrong.

Better score constants

---

src/bitboard.h

Remove functions for rook and bishop attack bitboards and let AttackBB handle all of it.

Cleanup AttackBB

---

src/bitboard.h
src/move.c
src/move.h
src/movegen.c
src/types.h

Move all the logic to find the relevant squares for the castling into CastlePseudoLegal() to achieve a much cleaner function signature. Should be just as fast due to inlining and constant propagation.

Refactor castling legality test

---

src/bitboard.c

Relies on the first step in the rook step array being 8 which isn't ideal, but better than the current solution.

Cleanup InitSliderAttack function signature

---

src/search.c

Reported seldepth now reflects the deepest node reaches in the last iteration, not in the whole search.

Fix seldepth

---

src/board.c
src/makemove.c

PositionOk asserts that each side has a king, and that the side to move cannot capture the enemy king.

Ensure 1 king each, and side to move can't capture the king

---

src/search.c
src/uci.c

Properly wait for stop when reaching max depth in an infinite search.

Wait for stop command in infinite search

---

src/evaluate.c
src/tests.c
src/tune.c
src/tune.h
src/uci.c

Weiss now has options to change evaluation parameters in dev mode. A 'uci' command must be sent before the options work, might change this in the future.
'eval' command now prints the score relative to white's point of view.

Evaluation tuneable in dev mode

---

src/types.h

Most notably, pawn value significantly down early and up late, and queen up overall.
ELO   | 3.79 +- 3.04 (95%)
Games | N: 27446 W: 7673 L: 7374 D: 12399
http://chess.grantnet.us/test/4996/
ELO   | 6.80 +- 4.87 (95%)
Games | N: 9508 W: 2414 L: 2228 D: 4866
http://chess.grantnet.us/test/4997/

Tune piece values

---

src/evaluate.c

ELO   | 4.05 +- 3.23 (95%)
Games | N: 22992 W: 6079 L: 5811 D: 11102
http://chess.grantnet.us/test/5018/
ELO   | 4.40 +- 3.16 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.50]
Games | N: 20688 W: 4753 L: 4491 D: 11444
http://chess.grantnet.us/test/5019/

Tune misc and passed bonuses

---

src/search.c

Now that evaluation is much better, many parts of search can be retuned.
ELO   | 14.05 +- 7.75 (95%)
Games | N: 3960 W: 1095 L: 935 D: 1930
http://chess.grantnet.us/test/5053/
ELO   | 8.07 +- 5.29 (95%)
Games | N: 7360 W: 1724 L: 1553 D: 4083
http://chess.grantnet.us/test/5055/

Shrink aspiration delta

---

src/tests.c

Removed arbitrary cap on depth in perft.

Allow higher depths in perft

---

src/search.c

Check whether we have run out of time for the current search every 4k nodes down from 8k. Also slightly better code.
ELO   | 1.89 +- 3.99 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=32MB
Games | N: 15968 W: 4439 L: 4352 D: 7177
http://chess.grantnet.us/test/5110/

Check for time up more often

---

src/evaluate.c

ELO   | 1.18 +- 1.42 (95%)
LLR   | -2.14 (-2.94, 2.94) [0.00, 4.00]
Games | N: 119200 W: 31346 L: 30942 D: 56912
http://chess.grantnet.us/test/5129/
ELO   | 2.95 +- 2.37 (95%)
SPRT  | 40.0+0.4s Threads=1 Hash=128MB
Games | N: 37986 W: 8935 L: 8613 D: 20438
http://chess.grantnet.us/test/5138/

Tune misc eval terms

---

src/bitboard.c
src/bitboard.h
src/board.c
src/makemove.c
src/search.c

Add a wrapper function for SquareAttacked() for checking if a king is attacked by the opponent's pieces to improve readability.
ELO   | 2.03 +- 3.32 (95%)
LLR   | 2.99 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 21712 W: 5681 L: 5554 D: 10477
http://chess.grantnet.us/test/5147/

KingAttacked function

---

src/bitboard.c
src/bitboard.h
src/evaluate.c

Replace nested for-loops with smarter code inspired by SF, and moved the init code to bitboard.c. I have doubts about the results of the test, but maybe code layout is improved.
ELO   | 12.08 +- 7.22 (95%)
Games | N: 4720 W: 1334 L: 1170 D: 2216
http://chess.grantnet.us/test/5165/

Cleanup eval bitmasks

---

src/board.c

Forgot an argument to KingAttacked in PositionOk().

Fix recent mistake in debug mode

---

src/search.c

ELO   | 4.04 +- 3.20 (95%)
Games | N: 21840 W: 5422 L: 5168 D: 11250
http://chess.grantnet.us/test/5207/
ELO   | 0.24 +- 1.90 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 4.00]
Games | N: 52776 W: 10871 L: 10834 D: 31071
http://chess.grantnet.us/test/5209/

No null move pruning in pv nodes

---

src/search.c

Underpromotions are grouped with quiet moves, and are not expected to be good given that a queen promotion was not. They were already pruned by LMP given they were ordered behind enough quiet moves, but the pruning could not happen exactly when the current move was an underpromo. This patch removes that check, allowing pruning also directly of underpromotions.
ELO   | 4.90 +- 4.61 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 10496 W: 2604 L: 2456 D: 5436
http://chess.grantnet.us/test/5224/
ELO   | 1.05 +- 2.40 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 33072 W: 6867 L: 6767 D: 19438
http://chess.grantnet.us/test/5225/

LMP underpromotions

---

src/evaluate.c
src/search.c
src/syzygy.h
src/transposition.h
src/types.h

Printed TB win scores are now 30000 minus ply-distance from root, and they are not scaled by pawn value, making them easier to understand.
Also cleaned up the score constant enum and names.

Cleanup scores

---

src/makemove.c

Avoid setting en passant if there is no pawn in position to actually use it. This allows slightly more transpositions as the same position right after a double pawn move will have the same hash as after shuffling pieces.
ELO   | 0.97 +- 2.56 (95%)
Games | N: 34544 W: 8495 L: 8399 D: 17650
http://chess.grantnet.us/test/5335/

Fix useless en passants in search

---

src/search.c

Weiss will now give updates during longer searches when failing high/low in root.
Also avoids lowering depth when failing high with a TB/Mate score. When such a score is first found it causes a long chain of fail highs, resulting in severely reduced depth which in turn can make the search unable to reach the TB/mate position anymore. Inspired by Ethereal.

Print updates during longer searches

---

src/fathom/tbchess.c
src/fathom/tbprobe.c
src/fathom/tbprobe.h
src/search.c
src/syzygy.h

Probe Syzygy DTZ tablebases and use the recommended move in root when made to search a position found in the tablebases. This means Weiss won't mess up a win or draw, but it might not play the best defense when losing, choosing the slowest, but possibly trivially easy, loss over the most difficult.

Probe Syzygy DTZ in root

---

src/movegen.c
src/movepicker.c
src/movepicker.h
src/search.c

Move killer move logic from movegen to movepicker. No need to generate quiet moves before trying them. Fixes moves with very good history being tried before killers (even if killers had better history).
ELO   | 7.35 +- 5.56 (95%)
Games | N: 7280 W: 1847 L: 1693 D: 3740
http://chess.grantnet.us/test/5504/

Try killer moves before generating quiets

---

src/movegen.c
src/movepicker.c
src/types.h

Move the scoring of moves out of movegen and into movepicker. Underpromotions now scored by history rather than MvvLva.
Plus a few small cleanups.
ELO   | 5.27 +- 4.79 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 9888 W: 2498 L: 2348 D: 5042
http://chess.grantnet.us/test/5521/
ELO   | 1.01 +- 2.34 (95%)
LLR   | 3.02 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 34539 W: 7121 L: 7021 D: 20397
http://chess.grantnet.us/test/5522/

Move scoring to movepicker

---

src/board.c
src/makemove.c
src/movegen.c
src/syzygy.h
src/types.h
src/uci.c

Reduce branching. Slightly cleaner code.
ELO   | 9.94 +- 6.47 (95%)
LLR   | 2.99 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 5664 W: 1530 L: 1368 D: 2766
http://chess.grantnet.us/test/5531/

Speedup make/takemove

---

src/tests.c

Can set hash size for bench by ./weiss bench [depth] [threads] [hash].

Allow changing hash size for bench

---

src/tests.c

Avoid counting time spent parsing FEN, clearing TT, etc.

Only count time spent searching in bench

---

src/fathom/tbconfig.h

Searching with multiple threads crashes when using tablebases. This should fix it, but there are still crashes, although rarer.

Turn on thread safety in fathom

---

src/evaluate.c
src/tune.c

Pawns on the same file are generally less effective than on separate files. This patch gives a penalty for having doubled pawns when one is right in front of the other.
ELO   | 4.42 +- 3.52 (95%)
Games | N: 18880 W: 4889 L: 4649 D: 9342
http://chess.grantnet.us/test/5767/
ELO   | 3.61 +- 2.89 (95%)
Games | N: 23984 W: 5308 L: 5059 D: 13617
http://chess.grantnet.us/test/5768/

Add doubled pawns to evaluation

---

src/search.c

A shorter search is a decent predictor for the result of the full-depth search we are about to make. If a shorter search shows a result sufficiently higher than beta, we can assume the full-depth search would also score above beta and prune the node immediately.
ELO   | 6.36 +- 4.59 (95%)
LLR   | 3.06 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10928 W: 2814 L: 2614 D: 5500
http://chess.grantnet.us/test/5806/
ELO   | 6.65 +- 4.63 (95%)
Games | N: 9098 W: 2006 L: 1832 D: 5260
http://chess.grantnet.us/test/5808/

ProbCut pruning

---

src/search.c

Avoid trying null move pruning if the transposition table indicates it will likely fail.
ELO   | 4.01 +- 3.21 (95%)
Games | N: 22536 W: 5771 L: 5511 D: 11254
http://chess.grantnet.us/test/5863/
ELO   | 7.62 +- 5.06 (95%)
Games | N: 7520 W: 1645 L: 1480 D: 4395
http://chess.grantnet.us/test/5865/

Improve NMP logic

---

src/search.c

Weiss doesn't try all moves when in check in quiescence search, so there's no point avoiding pruning as we're not proving checkmates either way.
ELO   | 4.96 +- 4.70 (95%)
Games | N: 10378 W: 2647 L: 2499 D: 5232
http://chess.grantnet.us/test/5876/
ELO   | 2.35 +- 3.22 (95%)
Games | N: 18771 W: 4008 L: 3881 D: 10882
http://chess.grantnet.us/test/5877/

Bench 41123182

---

src/uci.c

Signal search thread(s) to abort searching and wait for them to finish before exiting. The destructor for the TT would free the TT memory when the main thread exited, while search threads were still going, causing them to access free'd memory and crashing.

Graceful exit

---

src/transposition.c
src/types.h

The last patch fixed the case when Weiss is killed by sending it 'quit', but it did not fix segfaulting when killed by ctrl+c. This destructor is more hassle than being nice and freeing allocated memory on exit is worth - any modern OS will free everything when the program exits anyway so I will just remove it.

Graceful exit 2

---

src/uci.c

Avoid joining the search thread if it has never been spawned.

Graceful exit 3

---

src/tests.c
src/threads.c
src/transposition.c
src/transposition.h
src/uci.c

When search is allowed multiple threads, use the same amount to clear the transposition table. Should reduce initialization time when using big transposition table.

Multi-threaded TT clear

---

src/fathom/tbprobe.c
src/uci.c

Unsetting the syzygy path after setting it once left TB_LARGEST as non-0. Fixed this and switched to using the internal init print of fathom with more details.

Fix syzygy init bug

---

src/transposition.c

Quit would join a thread that had already been joined if given directly after a TT init occured.

Fix crashing if 'quit' given directly after TT init

---

src/search.c

Fixed a bug where threads that had already been joined were joined again when a move was gotten from DTZ tablebases or NoobBook.

Fix SMP + TB bug

---

src/search.c

Give a malus to quiet moves that failed to produce a cutoff if another quiet move manages to produce one.
ELO   | 37.49 +- 12.19 (95%)
Games | N: 1228 W: 308 L: 176 D: 744
http://chess.grantnet.us/test/6067/

Quiet history malus

---

src/search.c

Whenever the best move returned by search is different from the previous iteration, allocate more time to keep searching.
ELO   | 7.42 +- 5.11 (95%)
Games | N: 8472 W: 2113 L: 1932 D: 4427
http://chess.grantnet.us/test/6089/
ELO   | 2.91 +- 2.31 (95%)
Games | N: 35024 W: 7219 L: 6926 D: 20879
http://chess.grantnet.us/test/6091/

Spend more time when uncertain

---

src/uci.c

The cap is arbitrary, any number should work, and some people have machines with more than 256 cores so may as well be higher. 2048 for now.

Increase max threads

---

src/types.h

Leave a gap between mate and tb win scores so there is less chance for extended mate scores from TT to be treated as tb win scores.

Adjust internal scores

---

src/time.c

Weiss doesn't check the time situation before it has completed at least 1 search iteration (unless a depth 1 search takes more than 4096 nodes which is unlikely), so there's no reason to set a minimum thinking time.

Remove minimum thinking time

---

src/search.c
src/time.c
src/time.h

Currently game ply is reset to 0 whenever the 50 move rule resets, so the ply part of the time management which was intended to increase time usage as the game goes on, rather increases time usage the further we are from the last 50mr reset. Removing it shows no significant loss at normal time controls.
ELO   | -0.37 +- 1.15 (95%)
Games | N: 165966 W: 39451 L: 39629 D: 86886
http://chess.grantnet.us/test/6173/
ELO   | -0.03 +- 2.09 (95%)
LLR   | 1.34 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 41902 W: 8267 L: 8271 D: 25364
http://chess.grantnet.us/test/6174/

Simplify time management

---

src/time.c

Watching Weiss play cyclic time control I saw it didn't spend close to all its time before getting the next time increase. This patch fixes that, and apparently gains 500 elo in self-play...
ELO   | 687.51 +- 420.43 (95%)
SPRT  | 40/10.0s Threads=1 Hash=32MB
LLR   | 3.06 (-2.94, 2.94) [0.00, 5.00]
Games | N: 160 W: 155 L: 1 D: 4
http://chess.grantnet.us/test/6180/
ELO   | 499.68 +- 123.02 (95%)
SPRT  | 40/40.0s Threads=1 Hash=32MB
LLR   | 3.09 (-2.94, 2.94) [0.00, 5.00]
Games | N: 150 W: 135 L: 1 D: 14
http://chess.grantnet.us/test/6181/

Improve cyclic time management

---

src/time.c

ELO   | 3.91 +- 3.05 (95%)
SPRT  | 40/10.0s Threads=1 Hash=32MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 4.00]
Games | N: 24464 W: 6142 L: 5867 D: 12455
http://chess.grantnet.us/test/6185/
ELO   | 12.57 +- 6.26 (95%)
SPRT  | 40/40.0s Threads=1 Hash=32MB
Games | N: 5034 W: 1164 L: 982 D: 2888
http://chess.grantnet.us/test/6187/

Spend time slower (cyclic)

---

src/time.c

In the patch I tested I just sent 0 as ply to the old time management, when it passed I mistakenly left the wrong value when simplifying the relevant code.

Fix mistake in #303

---

src/time.c

Allow spending more time to finish a search iteration.
ELO   | 4.15 +- 3.18 (95%)
SPRT  | 40/10.0s Threads=1 Hash=32MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 4.00]
Games | N: 21616 W: 5222 L: 4964 D: 11430
http://chess.grantnet.us/test/6205/
ELO   | 2.69 +- 2.16 (95%)
SPRT  | 40/40.0s Threads=1 Hash=128MB
Games | N: 41120 W: 8724 L: 8406 D: 23990
http://chess.grantnet.us/test/6207/

Spend more time to finish iterations (cyclic)

---

src/time.c

Should be functionally equivalent.
ELO   | 2.00 +- 3.77 (95%)
LLR   | 3.01 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 15472 W: 3731 L: 3642 D: 8099
http://chess.grantnet.us/test/6212/
ELO   | -0.11 +- 3.12 (95%)
SPRT  | 40/10.0s Threads=1 Hash=32MB
LLR   | 1.42 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 22848 W: 5498 L: 5505 D: 11845
http://chess.grantnet.us/test/6213/

Simplify time management code

---

src/search.c

Use the same condition as for NMP - don't try if the TT info indicates it will fail.
ELO   | 1.33 +- 1.51 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 96096 W: 23045 L: 22678 D: 50373
http://chess.grantnet.us/test/6233/
ELO   | 2.54 +- 1.97 (95%)
Games | N: 47392 W: 9566 L: 9219 D: 28607
http://chess.grantnet.us/test/6237/

Tweak ProbCut

---

src/search.c

Inspired by an Ethereal patch by Alayant avoiding history updates if the first quiet at depth one fails high. Depth 1 searches are not very reliable, yet makes up a big part of the search tree, and as such they add a lot of noise to the history.
ELO   | 8.96 +- 5.79 (95%)
Games | N: 6672 W: 1700 L: 1528 D: 3444
http://chess.grantnet.us/test/6303/
ELO   | 2.29 +- 1.68 (95%)
Games | N: 65312 W: 13257 L: 12827 D: 39228
http://chess.grantnet.us/test/6307/

No history bonus for quiet moves that succeed on depth 1

---

src/evaluate.c

Give a bonus to pawns supported by other pawns.
Value not tuned, probably more elo by tuning it and other related values.
ELO   | 3.15 +- 2.48 (95%)
Games | N: 36736 W: 9133 L: 8800 D: 18803
http://chess.grantnet.us/test/6332/
ELO   | 2.29 +- 1.66 (95%)
Games | N: 69059 W: 14511 L: 14055 D: 40493
http://chess.grantnet.us/test/6336/

Support pawns

---

src/evaluate.c
src/tune.c

Added PawnSupport to the tuner and tuned that along with some other misc pawn terms.
ELO   | 2.00 +- 1.44 (95%)
Games | N: 107168 W: 25965 L: 25347 D: 55856
http://chess.grantnet.us/test/6869/
ELO   | 2.94 +- 2.35 (95%)
Games | N: 33552 W: 6865 L: 6581 D: 20106
http://chess.grantnet.us/test/6871/

Tune misc pawn terms

---

README.md
src/uci.c

I made Weiss claim it supported ponder to turn on ponder move hitrate tracking in cutechess GUI, but I haven't bothered looking at that in a long time so now I remove it to avoid any confusion it may cause. Weiss never supported pondering and I have no plans to add it as I don't find it useful or interesting.

Remove ponder print

---

src/transposition.c
src/uci.c

Over time, this issue led to a crash. On average, after about ~1800 games played on 8 Threads with 10+.01s time control, Weiss would crash due to resource issues caused by the hanging pthreads. This patch detaches the main search thread so that we can trust it to clean up its own resources. It removes a corresponding pthread_join() when issued a "stop" or "quit" command. 
A self-play test of ~5600 games with the same settings as above was done to confirm the fix. This same patch was applied to Ethereal to address the very same issue.

Resolve an issue where main threads may not be pthread_join()'ed

---

src/makefile

Automatically detect whether pext can (and should) be used. PGO is default target. Some cleanup.

Improve makefile

---

src/search.c

A score gotten from the TT will almost certainly be a better evaluation of the position than the static eval. If the score+bounds suggest a better evaluation then use that instead for pruning heuristics.
ELO   | 10.78 +- 6.91 (95%)
Games | N: 4966 W: 1347 L: 1193 D: 2426
http://chess.grantnet.us/test/7212/
ELO   | 12.09 +- 6.83 (95%)
Games | N: 4052 W: 898 L: 757 D: 2397
http://chess.grantnet.us/test/7213/
ELO   | 21.44 +- 9.52 (95%)
SPRT  | 20.0+0.2s Threads=8 Hash=512MB
LLR   | 2.95 (-2.94, 2.94) [-2.00, 3.00]
Games | N: 2126 W: 507 L: 376 D: 1243
http://chess.grantnet.us/test/7214/

Use score from TT instead of static eval if possible

---

src/makefile

PROPS will have znver mentioned on ryzens so no need for the other one.

Simplify makefile

---

src/search.c

Used https://github.com/kiudee/chess-tuning-tools to tune the qs futility margin for a pretty big gain.
ELO   | 12.70 +- 7.54 (95%)
Games | N: 4160 W: 1137 L: 985 D: 2038
http://chess.grantnet.us/test/7250/
ELO   | 12.00 +- 6.89 (95%)
Games | N: 4112 W: 939 L: 797 D: 2376
http://chess.grantnet.us/test/7251/

Tune qs futility margin

---

src/evaluate.c

Reduce tempo bonus from 20 to 15.
ELO   | 3.63 +- 3.50 (95%)
Games | N: 19024 W: 4879 L: 4680 D: 9465
http://chess.grantnet.us/test/7308/
ELO   | 4.37 +- 3.77 (95%)
LLR   | 3.02 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 13680 W: 2968 L: 2796 D: 7916
http://chess.grantnet.us/test/7310/

Lower tempo bonus

---

src/uci.c

Init TT on receiving go if not already done with isready. GUIs should send isready at least once before go, but for manual use this is a nice QoL upgrade.

QoL - No longer require isready before go

---

src/bitboard.c
src/bitboard.h
src/board.c
src/board.h
src/movepicker.c
src/movepicker.h
src/search.c
src/uci.h

Order seemingly bad noisy moves last using static exchange evaluation. SEE code inspired by Eth.
ELO   | 18.11 +- 9.13 (95%)
Games | N: 3034 W: 906 L: 748 D: 1380
http://chess.grantnet.us/test/7383/
ELO   | 22.39 +- 9.56 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2300 W: 595 L: 447 D: 1258
http://chess.grantnet.us/test/7384/

Sort bad noisy moves last

---

src/board.h
src/makemove.c
src/search.c
src/threads.c
src/threads.h
src/time.c

Changes the node counting to match SF exactly. Node count in bench is ~3% lower than before.

Count nodes in makemove

---

src/search.c

Once scores get very high or low just open the aspiration window completely in that direction for slightly improved mate detection.
No signifant change in playing strength.
ELO   | 1.85 +- 3.23 (95%)
Games | N: 22916 W: 5991 L: 5869 D: 11056
http://chess.grantnet.us/test/7412/
ELO   | -1.00 +- 3.69 (95%)
LLR   | 0.01 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 14588 W: 3116 L: 3158 D: 8314
http://chess.grantnet.us/test/7420/

Aspiration tweak

---

src/search.c
src/threads.h
src/uci.c

Get seldepth by checking history instead of incrementally updating it during search. Moves some code out of AB/QS which are huge and spreads it over other smaller functions. Maybe slightly faster.
ELO   | 1.60 +- 3.06 (95%)
Games | N: 25468 W: 6632 L: 6515 D: 12321
http://chess.grantnet.us/test/7438/

Get seldepth from history

---

src/search.c

If we are pressing for a win, and we make a move, they make a move, and we move back, unless one of these moves reset the 50 move rule (capture, pawn move), then they can repeat and get a fail high with score 0. So we give the takeback a score of 0 immediately.
There is a slight exception where a move can change castling rights without resetting the 50 move rule, but it does reset the 3-fold rule, but it seems that should be fine to ignore.
ELO   | 3.63 +- 3.52 (95%)
Games | N: 19520 W: 5205 L: 5001 D: 9314
http://chess.grantnet.us/test/7480/
ELO   | 5.43 +- 4.40 (95%)
Games | N: 10246 W: 2275 L: 2115 D: 5856 …

Upcoming repetition detection

---

src/search.c

No pruning nor reductions for the first few iterations of search. Widens the search and finds short tricks, improving puzzle solving a bit. Regresses at short time controls, will look into making the limit dynamic based on available time.
ELO   | -5.83 +- 4.43 (95%)
LLR   | -3.01 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 12048 W: 2981 L: 3183 D: 5884
http://chess.grantnet.us/test/7499/
ELO   | 4.04 +- 4.00 (95%)
LLR   | 3.00 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 12224 W: 2659 L: 2517 D: 7048
http://chess.grantnet.us/test/7500/

Full AB first few iterations of search

---

src/search.c
src/threads.h

Refactor to use a flag in thread to turn off pruning/reductions, and add a scaling based on time to fix the regression at short time controls the original version introduced. The linear scaling is unlikely to be optimal as nodes per depth doesn't scale linearly, so a better formula is probably possible, as is including nps and/or thread count in the calculation.
ELO   | 8.22 +- 5.96 (95%)
Games | N: 6891 W: 1906 L: 1743 D: 3242
http://chess.grantnet.us/test/7506/
ELO   | 1.11 +- 3.25 (95%)
LLR   | 0.12 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 19021 W: 4160 L: 4099 D: 10762
http://chess.grantnet.us/test/7510/

No early pruning tweak

---

src/board.h
src/search.c

Extend moves that seem to be forced. Helps discover the result of long forced lines earlier. Code inspired by SF, Eth and many other engines, they all seem to have a fairly similar implementations.
I tried adding this concept before, but it didn't work out, possibly due to poor eval.
ELO   | 11.52 +- 6.84 (95%)
Games | N: 5040 W: 1367 L: 1200 D: 2473
http://chess.grantnet.us/test/7577/
ELO   | 24.21 +- 9.83 (95%)
Games | N: 1984 W: 479 L: 341 D: 1164
http://chess.grantnet.us/test/7579/

Singular extension

---

src/search.c

Skip all moves in QS that are categorized as bad by SEE.
ELO   | 35.73 +- 12.73 (95%)
Games | N: 1376 W: 400 L: 259 D: 717
http://chess.grantnet.us/test/7613/
ELO   | 24.89 +- 9.66 (95%)
Games | N: 1888 W: 427 L: 292 D: 1169
http://chess.grantnet.us/test/7619/

Quiescence SEE pruning

---

src/search.c

Add a separate table for LMR reductions of captures, and reduce them less than before.
ELO   | 11.55 +- 7.02 (95%)
Games | N: 4512 W: 1158 L: 1008 D: 2346
http://chess.grantnet.us/test/7672/
ELO   | 5.07 +- 4.06 (95%)
Games | N: 10688 W: 2117 L: 1961 D: 6610
http://chess.grantnet.us/test/7673/

Separate LMR for captures

---

src/movepicker.c
src/search.c
src/threads.h

Switch from piece-to history to butterfly history.
ELO   | 4.69 +- 4.09 (95%)
Games | N: 13040 W: 3170 L: 2994 D: 6876
http://openbench.sassytheo.com/test/7680/
ELO   | 12.81 +- 6.93 (95%)
Games | N: 3744 W: 796 L: 658 D: 2290
http://openbench.sassytheo.com/test/7691/

Butterfly history

---

src/search.c

Quiets are already reduced by a full 1 ply more base, and with a steeper curve, but captures are apparently still reduced too much.
ELO   | 7.07 +- 5.28 (95%)
Games | N: 7712 W: 1869 L: 1712 D: 4131
http://openbench.sassytheo.com/test/7693/
ELO   | 7.92 +- 5.28 (95%)
Games | N: 6272 W: 1255 L: 1112 D: 3905
http://openbench.sassytheo.com/test/7695/

Lower base LMR of captures

---

src/search.c

Lower the curve yet again.
ELO   | 5.77 +- 4.67 (95%)
Games | N: 10048 W: 2460 L: 2293 D: 5295
http://chess.grantnet.us/test/7697/
ELO   | 3.43 +- 3.16 (95%)
Games | N: 17536 W: 3415 L: 3242 D: 10879
http://chess.grantnet.us/test/7698/

Lower curve LMR of Captures

---

src/search.c

No bonus for moves that beat alpha.
ELO   | 3.12 +- 3.04 (95%)
LLR   | 3.04 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 23248 W: 5496 L: 5287 D: 12465
http://chess.grantnet.us/test/7810/
ELO   | 4.61 +- 3.79 (95%)
Games | N: 12144 W: 2365 L: 2204 D: 7575
http://chess.grantnet.us/test/7815/

History bonus only on beta cut

---

src/search.c

Start the LMR of captures at zero, but increase the curve slightly.
ELO   | 4.00 +- 3.68 (95%)
Games | N: 16144 W: 3916 L: 3730 D: 8498
http://chess.grantnet.us/test/7831/
ELO   | 2.59 +- 2.57 (95%)
Games | N: 26384 W: 5053 L: 4856 D: 16475
http://chess.grantnet.us/test/7832/

Lower base LMR of captures again

---

src/search.c
src/search.h
src/uci.c

Also works for getting mated in x. Can fail if Weiss thinks it's getting mated in x or fewer moves, when it should be a mating in x, but this should be extremely rare, if at all possible.
No impact on playing strength.

Support 'go mate x'

---

src/board.c
src/board.h
src/evaluate.c
src/evaluate.h
src/makemove.c
src/search.c
src/tests.c
src/threads.c
src/threads.h
src/tuner/tuner.c
src/uci.c

Pawn evaluation doesn't depend on any other pieces, and doesn't change too often so caching it and reusing it later is a nice speedup. Gets about 80-90% hitrate depending on position.
ELO   | 10.11 +- 6.10 (95%)
LLR   | 3.06 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5776 W: 1427 L: 1259 D: 3090

Pawn cache

---

src/tests.c
src/tests.h
src/uci.c
src/uci.h

Major refactor of Perft() - now uses the movepicker which is a lot slower, but testing it is valuable. MirrorTest() retired.

Cleanup tests

---

src/search.c

When getting mated the given value is supposed to be negative. This solution still allows finding a mate for the wrong side, but I still think that's unlikely enough, if not impossible, that it's not worth worrying about.

Fix mate x

---

src/search.c
src/tuner/tuner.c
src/tuner/tuner.h

Update bestmove before aborting search in go mate. Often the mate found starts with the best move of the previous iteration, but not always. Also for mate in 1 it would print a1a1 as bestmove would be 0.
Also added a link to @AndyGrant 's paper on eval tuning.

Fix go mate

---

src/tests.c

Made a python script to test perft on fens from a file, seems most others print either just the nodecount alone, or following a token like "Nodes:" so to make it easy to use the script with other engines I'll make the prints of Weiss more standard, and let the script expect that.

Change perft print to be more similar to others

---

src/makefile

Give proper arguments to clang for pgo.
Weiss is much slower when compiled by Clang, but hey at least it works now.

Fix PGO for clang

---

src/search.c

In positions the TB says are losing weiss keeps searching to see if it's even worse (getting mated), but can also fail to see that it's losing at all. This avoids returning a score that's better than TB loss in such a situation.

Fix TB scoring

---

src/search.c

Only has an effect at ply 1 as improving isn't used in root. Improving is now true at ply 1 when not in check and eval > 0.

Simplify improving

---

src/search.c
src/threads.h

Fix history scores overflowing. Formula from Ethereal.
Testing with [-5, 0]:
ELO   | 11.05 +- 7.87 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 3648 W: 947 L: 831 D: 1870
http://chess.grantnet.us/test/9366/
ELO   | 10.39 +- 6.89 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 3680 W: 750 L: 640 D: 2290
http://chess.grantnet.us/test/9367/

History score decay

---

src/search.c

Give a history bonus to the TT move when cutting with TT info.
ELO   | 4.58 +- 3.61 (95%)
Games | N: 17312 W: 4344 L: 4116 D: 8852
http://chess.grantnet.us/test/9422/
ELO   | 1.55 +- 1.57 (95%)
Games | N: 70944 W: 13657 L: 13340 D: 43947
http://chess.grantnet.us/test/9424/

History tt cut bonus

---

src/uci.c

Noticed node count was different when setting up with FEN instead of startpos + moves. Fixed by resetting node count to 0 after parsing moves.

Don't count nodes while setting up position

---

src/search.c

Count all moves instead of only quiets for LMP.
ELO   | 4.19 +- 3.81 (95%)
Games | N: 15168 W: 3702 L: 3519 D: 7947
ELO   | 4.50 +- 3.76 (95%)
Games | N: 12280 W: 2380 L: 2221 D: 7679

LMP based on total move count

---

src/evaluate.c

STC:
ELO   | 4.83 +- 3.79 (95%)
Games | N: 16833 W: 4509 L: 4275 D: 8049
http://chess.grantnet.us/test/10000/
LTC:
ELO   | 11.66 +- 6.53 (95%)
Games | N: 4592 W: 1048 L: 894 D: 2650
http://chess.grantnet.us/test/10002/

Increase KingAttackPower each possible check

---

src/evaluate.c
src/uci.h

STC:
ELO   | 2.33 +- 2.40 (95%)
Games | N: 36814 W: 8535 L: 8288 D: 19991
http://chess.grantnet.us/test/10063/
LTC:
ELO   | 2.67 +- 2.59 (95%)
Games | N: 24444 W: 4439 L: 4251 D: 15754
http://chess.grantnet.us/test/10087/

Start king attack power at a value of -30

---

src/search.c

Reduce less while trying killers because they are likely to cause a re-search
Passed STC:
ELO   | 3.67 +- 3.46 (95%)
LLR   | 2.94 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 17596 W: 4105 L: 3919 D: 9572
http://chess.grantnet.us/test/10147/
Passed LTC:
ELO   | 4.74 +- 3.52 (95%)
Games | N: 13186 W: 2417 L: 2237 D: 8532
http://chess.grantnet.us/test/10149/

Reduce less for killers

---

src/search.c

ELO   | 1.73 +- 3.59 (95%)
LLR   | 2.97 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 16646 W: 3898 L: 3815 D: 8933
ELO   | 0.74 +- 2.47 (95%)
LLR   | 3.00 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 27204 W: 4912 L: 4854 D: 17438

Simplify pruning condition

---

src/search.c

Finished testing slightly negative, but it's a fairly unique feature so I'll take the slight loss in order to increase the effect of it.
ELO   | -0.91 +- 2.64 (95%)
LLR   | -2.99 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 24464 W: 4469 L: 4533 D: 15462

No pruning iteration 7

---

src/makefile

New ryzens have fast pext so they should compile with pext.

Compile with pext on new ryzen cpus

---

src/search.c
src/tests.c

Mainly to avoid low nps in fixed depth searches.

Allow helper threads to search past the depth limit

---

src/movepicker.c
src/noobprobe/noobprobe.c
src/noobprobe/noobprobe.h
src/search.c
src/search.h
src/syzygy.h
src/tests.c
src/threads.c
src/threads.h
src/transposition.c
src/transposition.h
src/uci.c
src/uci.h

There's no reason to have more than one set of threads so they are now global, avoiding sending them around everywhere. Also moved all implementation specific code (usage of pthread library) to threads.c.

Global threads

---

src/search.c

Only give a history bonus to the tt move if we are failing high with it.
ELO   | 2.45 +- 2.52 (95%)
Games | N: 34440 W: 8280 L: 8037 D: 18123
ELO   | 3.29 +- 3.07 (95%)
LLR   | 2.94 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 18376 W: 3520 L: 3346 D: 11510

TT cut history bonus tweak

---

src/search.c

Change caused by a silly loss to Halogen at TCEC due to null move pruning in zugzwang, immediately losing a dead drawn position.
ELO   | -0.22 +- 2.98 (95%)
LLR   | 1.17 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 22544 W: 4871 L: 4885 D: 12788
ELO   | 2.11 +- 3.29 (95%)
Games | N: 14688 W: 2563 L: 2474 D: 9651

Disable nullmove at high depth with 1 piece left

---

src/threads.c
src/threads.h

Since the change to history updates, the history won't overflow anymore and is quicker to adapt to changes in the search tree so keeping it from turn to turn finally works out.
ELO   | 11.45 +- 6.81 (95%)
Games | N: 4464 W: 1072 L: 925 D: 2467
ELO   | 7.54 +- 4.95 (95%)
Games | N: 6448 W: 1172 L: 1032 D: 4244

Keep history from previous turn

---

src/evaluate.c
src/tuner/tuner.c
src/tuner/tuner.h

Give a bonus for pawns attacking non-pawns.
ELO   | 13.13 +- 7.40 (95%)
Games | N: 3840 W: 945 L: 800 D: 2095
ELO   | 8.19 +- 5.26 (95%)
Games | N: 5984 W: 1140 L: 999 D: 3845

Pawn Threats

---

src/evaluate.c

OpenBench now supports use of Syzygy during testing, and all tournaments use it too, so specialized code for endgames is now redundant.

Retire MaterialDraw

---

src/threads.c
src/uci.c

At ply 100, ss->ply was left at 0 making search miss the fact that it was at max ply. PrintThinking assumed max ply was 100 and didn't bother checking for higher, hiding the fact that search went out of bounds.
Fixed the bug and prints will now indicate if search goes beyond 100.

Fix going past max ply

---

src/search.c
src/threads.c
src/threads.h

Reduce an extra ply for the side that last null moved. This side is trying to claim that it is much better, yet the non-lmr'd moves have already failed. Likely it will keep failing, so spend less time on it.
Idea from Koivisto.
ELO   | 1.57 +- 2.14 (95%)
LLR   | 1.53 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 45360 W: 10282 L: 10077 D: 25001
ELO   | 5.29 +- 4.06 (95%)
Games | N: 9856 W: 1809 L: 1659 D: 6388

Null mover LMR

---

src/search.c

Give most draws a small positive random score to make the side playing into the draw explore more alternatives, hopefully finding a way to avoid it when better, or being more certain of the draw when behind.
ELO   | 3.12 +- 2.95 (95%)
Games | N: 19840 W: 3802 L: 3624 D: 12414
ELO   | 5.27 +- 4.36 (95%)
Games | N: 11264 W: 2698 L: 2527 D: 6039

Draw Contempt

---

src/time.c

Openbench now supports Syzygy TBs for tests, but most workers have them on HDDs which is very slow and rare time outs have happened. To combat this I'm doubling the frequency at which time is checked, and increasing overhead by 1 ms. The increased overhead might gain a couple elo at very fast time controls.
ELO   | 1.33 +- 3.39 (95%)
Games | N: 19328 W: 4682 L: 4608 D: 10038

More careful with time

---

src/search.c

All moves in QSearch have to have a static exchange evaluation greater than or equal to 0. Now requires it to be greater than 0 if static eval is significantly below alpha.
ELO   | 5.74 +- 4.64 (95%)
Games | N: 10172 W: 2490 L: 2322 D: 5360
ELO   | 1.50 +- 2.12 (95%)
LLR   | 1.53 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 38848 W: 7403 L: 7235 D: 24210

Quiescence Futility

---

src/movepicker.c
src/search.c
src/threads.c
src/threads.h

Order noisy moves by history heuristics much like quiet moves. The slowdown hurts STC, but LTC shows decent gain.
ELO   | -4.17 +- 4.83 (95%)
LLR   | -3.01 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 9088 W: 2028 L: 2137 D: 4923
ELO   | 3.66 +- 3.29 (95%)
Games | N: 15936 W: 3052 L: 2884 D: 10000

Capture History

---

src/movepicker.c

Classify captures with extremely good history as good, regardless of static exchange evaluation.
ELO   | 2.81 +- 2.80 (95%)
LLR   | 3.04 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 27536 W: 6538 L: 6315 D: 14683
ELO   | 4.23 +- 3.56 (95%)
Games | N: 13316 W: 2517 L: 2355 D: 8444

Classify captures with history

---

src/movepicker.c

Use just the value of the captured piece in place of MvvLva.
ELO   | 1.46 +- 3.08 (95%)
LLR   | 2.97 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 18528 W: 3549 L: 3471 D: 11508

Simplify noisy move scoring

---

src/transposition.c

Most engines use something like depth + 4 > tte->depth, this failed in weiss a long time ago. Now it seems to work, but this is even better.
Idea from Berserk author.
ELO   | 9.46 +- 5.82 (95%)
Games | N: 5144 W: 1040 L: 900 D: 3204

Tweak TT replacement scheme

---

src/evaluate.c
src/tuner/tuner.c
src/tuner/tuner.h

Give a bonus for kings attacking one or more pawns.
ELO   | 8.40 +- 5.89 (95%)
Games | N: 6456 W: 1642 L: 1486 D: 3328
ELO   | 11.36 +- 6.45 (95%)
Games | N: 4284 W: 896 L: 756 D: 2632

King threatening pawn

---

src/bitboard.h
src/evaluate.c
src/tuner/tuner.c
src/tuner/tuner.h

Undefended, unopposed pawns are targets for constant pressure by rooks and queens.
ELO   | 10.39 +- 6.58 (95%)
Games | N: 5116 W: 1300 L: 1147 D: 2669
ELO   | 5.81 +- 4.40 (95%)
Games | N: 9036 W: 1788 L: 1637 D: 5611

Penalize undefended, unopposed pawns

---

src/search.c

Prune moves with bad SEE.
ELO   | 8.69 +- 5.97 (95%)
Games | N: 6120 W: 1517 L: 1364 D: 3239
ELO   | 6.08 +- 4.52 (95%)
Games | N: 8568 W: 1694 L: 1544 D: 5330

Static exchange evaluation pruning

---

src/search.c

Skip moves with bad history at low depths.
ELO   | 9.05 +- 5.99 (95%)
Games | N: 5680 W: 1325 L: 1177 D: 3178
ELO   | 10.50 +- 6.09 (95%)
Games | N: 4568 W: 905 L: 767 D: 2896

History pruning

---

src/search.c

Allows more aggressive pruning. May or may not just be making up for pruning being too conservative in general.
ELO   | 2.87 +- 2.79 (95%)
Games | N: 26168 W: 5865 L: 5649 D: 14654
ELO   | 2.37 +- 2.37 (95%)
Games | N: 29152 W: 5258 L: 5059 D: 18835

IIR before forward pruning

---

src/search.c

Adjust LMR reduction by between +2 and -2 based on move history.
ELO   | 14.11 +- 7.57 (95%)
Games | N: 3448 W: 805 L: 665 D: 1978
ELO   | 13.90 +- 7.06 (95%)
Games | N: 3352 W: 672 L: 538 D: 2142

Adjust LMR by move history

---

src/search.c

ELO   | 4.94 +- 4.17 (95%)
Games | N: 11600 W: 2610 L: 2445 D: 6545
ELO   | 3.92 +- 3.37 (95%)
Games | N: 14176 W: 2553 L: 2393 D: 9230

Adjust LMR by move history more aggressively

---

src/search.c

ELO   | 2.77 +- 2.67 (95%)
Games | N: 22416 W: 3958 L: 3779 D: 14679
ELO   | 6.31 +- 4.83 (95%)
Games | N: 8648 W: 1966 L: 1809 D: 4873

Do per-move pruning in PV nodes

---

src/evaluate.c

Give bonus for number of pawns defending pawns rather than number of defended pawns.
ELO   | 3.12 +- 3.00 (95%)
LLR   | 3.04 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 22280 W: 4916 L: 4716 D: 12648

Tweak pawn support term

---

src/search.c

Allows pruning at high depths if LMR would reduce the searched depth enough.
ELO   | 4.01 +- 3.40 (95%)
GAMES | N: 13680 W: 2412 L: 2254 D: 9014

Use approximate LMR depth for pruning margins

---

src/movepicker.c

Classify noisy moves as bad if they have bad history, regardless of SEE.
ELO   | 3.51 +- 3.30 (95%)
GAMES | N: 17904 W: 3856 L: 3675 D: 10373
ELO   | 5.68 +- 4.21 (95%)
GAMES | N: 8864 W: 1578 L: 1433 D: 5853

Bad history -> bad noisy

---

src/history.h

Allowing noisy killers leads to possibly playing moves twice.

Bugfix: No noisy killer moves

---

src/evaluate.c
src/tuner/tuner.c
src/tuner/tuner.h

Give a bonus for pawns that can attack non-pawn pieces by moving forward.
ELO   | 6.18 +- 4.78 (95%)
GAMES | N: 8880 W: 2029 L: 1871 D: 4980
ELO   | 3.02 +- 2.82 (95%)
GAMES | N: 19896 W: 3501 L: 3328 D: 13067

Push threat

---

src/search.c

Smaller reduction of beta after a fail-low.
ELO   | 3.34 +- 2.96 (95%)
GAMES | N: 17048 W: 2839 L: 2675 D: 11534

Fail-low beta reduction tweak

---

src/search.c

Try fewer moves before giving up on quiet moves.
ELO   | 4.21 +- 3.71 (95%)
GAMES | N: 13944 W: 2977 L: 2808 D: 8159
ELO   | 4.16 +- 3.41 (95%)
GAMES | N: 12848 W: 2155 L: 2001 D: 8692

Quiet LMP sooner

---

src/history.h
src/movepicker.c
src/threads.c
src/threads.h

Give a history score based on how well a move does given the opponents previous move.
ELO   | 44.68 +- 14.02 (95%)
GAMES | N: 1040 W: 295 L: 162 D: 583
ELO   | 33.95 +- 10.83 (95%)
GAMES | N: 1304 W: 280 L: 153 D: 871

Counter move history

---

src/history.h
src/movepicker.c

Give a history score based on how well a move does given our own previous move.
ELO   | 14.31 +- 7.60 (95%)
GAMES | N: 3400 W: 790 L: 650 D: 1960
ELO   | 4.14 +- 3.38 (95%)
GAMES | N: 12760 W: 2084 L: 1932 D: 8744

Followup move history

---

src/search.c

With the additional history heuristics, quiet move ordering is much better than before, and late moves are thus less likely to be good.
ELO   | 7.37 +- 5.19 (95%)
GAMES | N: 7024 W: 1511 L: 1362 D: 4151
ELO   | 4.88 +- 3.76 (95%)
GAMES | N: 10400 W: 1722 L: 1576 D: 7102

LMR reduce more for late quiet moves

---

src/search.c

ELO   | 2.62 +- 2.60 (95%)
GAMES | N: 27288 W: 5556 L: 5350 D: 16382
ELO   | 4.79 +- 3.67 (95%)
GAMES | N: 10528 W: 1691 L: 1546 D: 7291

LMR history adjustment tweak

---

src/search.c

ELO   | 6.33 +- 4.67 (95%)
LLR   | 3.02 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 8448 W: 1756 L: 1602 D: 5090
ELO   | 3.48 +- 3.00 (95%)
GAMES | N: 15584 W: 2438 L: 2282 D: 10864

Lower the history pruning margin

---

src/search.c

ELO   | 3.28 +- 2.90 (95%)
GAMES | N: 16864 W: 2673 L: 2514 D: 11677
ELO   | 5.25 +- 4.22 (95%)
GAMES | N: 10392 W: 2154 L: 1997 D: 6241

ProbCut only try good noisy moves

---

src/movepicker.c
src/movepicker.h
src/search.c

Don't bother sorting moves with bad history at low depths.
ELO   | 12.27 +- 6.80 (95%)
GAMES | N: 3936 W: 844 L: 705 D: 2387
ELO   | 4.47 +- 3.51 (95%)
LLR   | 3.02 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 11728 W: 1904 L: 1753 D: 8071

Lazy move sorting

---

src/history.h
src/movepicker.c
src/search.c

Killers were using the history of the last good noisy move instead of their own. Also removes the value of the captured piece for capture history in search.
ELO   | 3.16 +- 3.02 (95%)
GAMES | N: 20432 W: 4223 L: 4037 D: 12172
ELO   | 6.91 +- 4.47 (95%)
GAMES | N: 6792 W: 1066 L: 931 D: 4795

Fix killer history

---

src/evaluate.c

A mistake led to king zone being extended backwards. This removes the extension.

Simplify king zone

---

src/history.h

When a previous move was null or there was no previous move history, history of the piece on A1 moving to A1 was used instead.

History bugfix

---

src/history.h

ELO   | 4.31 +- 3.73 (95%)
GAMES | N: 13384 W: 2779 L: 2613 D: 7992
ELO   | 3.61 +- 3.08 (95%)
LLR   | 2.94 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 14728 W: 2296 L: 2143 D: 10289

No history bonus at depth 2 or lower

---

src/history.h

ELO   | 2.39 +- 2.43 (95%)
GAMES | N: 31448 W: 6426 L: 6210 D: 18812
ELO   | 1.36 +- 1.40 (95%)
GAMES | N: 71384 W: 10901 L: 10622 D: 49861

No capture history bonus at depth 2 or lower

---

src/search.c

Always prove terminal win scores.

Avoid returning winning score by pruning

---

src/search.c

ELO   | 8.39 +- 5.52 (95%)
GAMES | N: 6008 W: 1262 L: 1117 D: 3629
ELO   | 5.10 +- 3.75 (95%)
GAMES | N: 9880 W: 1557 L: 1412 D: 6911

Lower reverse futility pruning margin

---

src/search.c

ELO   | 3.30 +- 3.11 (95%)
GAMES | N: 18832 W: 3791 L: 3612 D: 11429
ELO   | 0.97 +- 1.72 (95%)
LLR   | 0.69 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 47408 W: 7223 L: 7090 D: 33095

Lower razor margin

---

src/bitboard.h

Queens are terrible blockers, so ignore them for slider mobility.
ELO   | 3.28 +- 3.10 (95%)
GAMES | N: 18848 W: 3772 L: 3594 D: 11482
ELO   | 6.90 +- 4.51 (95%)
GAMES | N: 6952 W: 1134 L: 996 D: 4822

X-ray enemy queens for mobility

---

src/search.c
src/threads.h

Spend at most half a second on forced moves.
Closes #500 
ELO   | 1.43 +- 2.68 (95%)
GAMES | N: 19192 W: 2893 L: 2814 D: 13485

Limit time spent on forced moves

---

src/uci.c

Helps SCID parse the different multipv lines.

Add 'multipv n' to thinking info prints

---

src/search.c

Center the aspiration window of each multipv search around the previous score of that pv index, instead of centering all of them around the best move.
ELO   | 13.16 +- 7.62 (95%)
GAMES | N: 3936 W: 1045 L: 896 D: 1995

Multi-PV aspiration window improvement

---

src/search.c

Instead of temporarily doubling the time before not attempting to start the next depth, just keep starting the next depth as long as we are uncertain.
ELO   | 3.48 +- 2.95 (95%)
GAMES | N: 15568 W: 2360 L: 2204 D: 11004

Keep searching when uncertain

---

src/search.c

As seen in Bit Genie.
ELO   | 1.82 +- 1.89 (95%)
GAMES | N: 50328 W: 9876 L: 9612 D: 30840
ELO   | 2.21 +- 2.17 (95%)
GAMES | N: 29072 W: 4408 L: 4223 D: 20441

Reverse futility pruning tweak

---

src/search.c
src/search.h
src/uci.c

Adds support for `go searchmoves <moves>` which restricts the moves searched in the root position.
Goes well with Nibbler GUI.

Searchmoves

---

src/uci.c

When MultiPV is set higher than the number of legal moves in root (or the number of searchmoves) some pvs will be empty as nothing was searched. This avoids printing those as they are pointless.

Avoid printing empty PVs

---

src/search.c
src/threads.c

It seems the time limit for only-moves was sometimes applied even when there were multiple root moves at TCEC. As seen in SuFi testing games for season 21. I have no idea how that could happen, and I was unable to reproduce the behavior.
To avoid this just count root moves before starting the search instead of relying on number of moves searched in root.

Count root moves before search

---

src/evaluate.c

Use distance to the square in front of the passer, as supporting or preventing the pawn's advance is important.
ELO   | 2.24 +- 2.32 (95%)
GAMES | N: 36792 W: 7981 L: 7744 D: 21067

Passed king distance tweak

---

src/evaluate.c

ELO   | 1.91 +- 1.98 (95%)
GAMES | N: 50536 W: 10937 L: 10659 D: 28940
ELO   | 2.89 +- 2.70 (95%)
GAMES | N: 20448 W: 3386 L: 3216 D: 13846

Bonus for passed pawns defended by pawns

---

src/search.c

ELO   | 3.33 +- 2.96 (95%)
GAMES | N: 16672 W: 2720 L: 2560 D: 11392

LMR quiets more when ttMove is a capture

---

src/search.c
src/threads.c
src/threads.h
src/uci.c

When there were fewer legal (or restricted by searchmoves) moves than MultiPV and the scores of the searched moves were negative they would be sorted behind empty moves, and skipped in printing. This patch includes the searchmoves restriction when counting rootmoves, and sorts at most as many PVs as there are rootmoves.

Fix bug with MultiPV

---

src/search.c

ELO   | 3.88 +- 3.49 (95%)
GAMES | N: 15680 W: 3325 L: 3150 D: 9205
ELO   | 3.31 +- 2.95 (95%)
GAMES | N: 17112 W: 2836 L: 2673 D: 11603

Begin LMR 1 move later in root

---

src/evaluate.c
src/uci.h

ELO   | 3.46 +- 3.03 (95%)
GAMES | N: 15880 W: 2583 L: 2425 D: 10872

Scale down OCB endgames with one extra piece each

---

src/history.h
src/move.c
src/move.h
src/movegen.c
src/syzygy.h

This makes sure killers and tt moves actually match the current position, and fixes a bug with follow-up move (2 ply back) history where when the moved piece was captured by the counter-move (1 ply back), the move was using the counter-move history twice instead of fmh and cmh.

Encode moving piece in the move

---

src/move.c
src/transposition.c
src/transposition.h

Now that the move encodes the moving piece, it's much simpler to check if a move makes sense in the current position or not.

Cleanup MoveIsPseudoLegal

---

src/search.c

Snapshot the full entry directly after probing to reduce the chance a different thread overwrites the data before it is read. Has no impact on strength playing with 8 threads, but maybe it matters for TCEC-like conditions.

Snapshot TT entry

---

src/movepicker.c
src/search.c

The pseudo-legality check is now cheaper than before, so the cost of validating the tt move earlier is low enough that it doesn't seem to matter. Validating the tt move earlier is an extra hedge against hash collisions, as well as against mismatched entries caused by data races when using multiple threads. I doubt this matters for playing strength, but maybe in conditions like at TCEC it makes a difference.

Validate move from TT earlier

---

src/bitboard.h
src/evaluate.c

Scale down the eval if the stronger side doesn't have pawns on both sides of the board.
-20 vs -10
ELO   | 5.22 +- 3.89 (95%)
GAMES | N: 9576 W: 1572 L: 1428 D: 6576
-10 vs master
ELO   | 5.33 +- 3.93 (95%)
LLR   | 3.03 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 9656 W: 1628 L: 1480 D: 6548

Eval scale tweak

---

src/transposition.c

Depth + 4 (or around there) is the standard, but a while back depth * 2 tested better. After recent changes it seems the flat offset is doing better again.
ELO   | 2.91 +- 2.83 (95%)
GAMES | N: 22768 W: 4574 L: 4383 D: 13811
ELO   | 2.08 +- 2.07 (95%)
GAMES | N: 32040 W: 4857 L: 4665 D: 22518

Switch back to flat depth offset for TT replacement

---

src/search.c
src/search.h
src/uci.c

Fixes a crash when the engine is told to stop and immediately start a new search.
Thanks to mrbdzz / skiminki for the report and the fix.

Wait for the search to complete on UCI stop command

---

src/syzygy.h

DTZ is given as moves until zeroing 50mr rule in the position before the move, subtracting one to give the distance after the chosen move.

Fix score when playing moves from syzygy

---

src/search.c

Quiet moves after the 32nd were remembered as noisy moves, wasting time updating scores that were never used, and preventing noisy moves from being remembered.
ELO   | 0.81 +- 1.32 (95%)
LLR   | -2.95 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 138048 W: 36178 L: 35857 D: 66013

Fix bug with history scoring

---

src/search.c

Stricter than the old condition. Since the score has to beat not just `beta`, but `beta + 200`, if the score from TT is an upper bound lower than this, the ProbCut is very unlikely to succeed.
ELO   | 2.29 +- 2.37 (95%)
GAMES | N: 42800 W: 11250 L: 10968 D: 20582

Improve ProbCut condition

---

src/search.c

Reducing by 2 in pv nodes beat master:
ELO   | 3.54 +- 3.45 (95%)
GAMES | N: 20512 W: 5533 L: 5324 D: 9655
ELO   | 4.30 +- 3.89 (95%)
GAMES | N: 14792 W: 3675 L: 3492 D: 7625
And reducing by 1 beat that (yellow LTC):
ELO   | 1.67 +- 1.58 (95%)
GAMES | N: 99584 W: 26941 L: 26462 D: 46181
ELO   | 0.25 +- 2.01 (95%)
LLR   | -2.96 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 55384 W: 13450 L: 13410 D: 28524

Only IIR in pv nodes

---

src/history.h

Give more bonus at low depth, and limit the maximum bonus given.
ELO   | 23.19 +- 10.49 (95%)
LLR   | 3.05 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 2296 W: 701 L: 548 D: 1047
ELO   | 14.72 +- 8.05 (95%)
GAMES | N: 3448 W: 904 L: 758 D: 1786

New history bonus formula

---

src/search.c

Require static eval to be higher at low depths in order to attempt null move pruning.
ELO   | 3.44 +- 3.37 (95%)
GAMES | N: 21736 W: 5912 L: 5697 D: 10127
ELO   | 4.41 +- 3.95 (95%)
GAMES | N: 14168 W: 3483 L: 3303 D: 7382

Tweak NMP condition

---

src/search.c

Try NMP even when static eval is below beta at higher depths as long as the TT score still beats beta.
ELO   | 4.21 +- 3.92 (95%)
GAMES | N: 16112 W: 4413 L: 4218 D: 7481
ELO   | 0.92 +- 3.61 (95%)
LLR   | 3.00 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 17288 W: 4223 L: 4177 D: 8888

Simplify NMP condition

---

src/search.c
src/threads.h

If the opponent's previous move's history is good, it's unlikely we can pass our turn and still be winning.
Probably matters more at LTC because higher depths are reached, where the condition on static eval is loosened a lot.
(STC 25000, LTC 35000)
ELO   | 2.74 +- 2.81 (95%)
GAMES | N: 31072 W: 8385 L: 8140 D: 14547
ELO   | 9.31 +- 6.26 (95%)
GAMES | N: 5784 W: 1494 L: 1339 D: 2951

No NMP if previous move has good hist score

---

src/search.c

ELO   | 1.55 +- 2.46 (95%)
LLR   | 0.92 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 40816 W: 11016 L: 10834 D: 18966
ELO   | 3.27 +- 3.19 (95%)
GAMES | N: 21784 W: 5333 L: 5128 D: 11323

Tweak NMP static eval condition

---

src/evaluate.c
src/tuner/tuner.c
src/tuner/tuner.h

Use the square rule when only pawns are left to help determine if passed pawns are queening.
ELO   | 5.28 +- 4.57 (95%)
GAMES | N: 11856 W: 3261 L: 3081 D: 5514
ELO   | 3.63 +- 3.48 (95%)
GAMES | N: 18752 W: 4695 L: 4499 D: 9558

Square rule for passed pawns

---

src/evaluate.c
src/tuner/tuner.h

Tuned all params, but only kept the changes to these.
ELO   | 3.31 +- 3.29 (95%)
GAMES | N: 23416 W: 6521 L: 6298 D: 10597
ELO   | 5.72 +- 4.71 (95%)
GAMES | N: 10384 W: 2666 L: 2495 D: 5223

Tune some eval terms

---

src/evaluate.c
src/movepicker.c
src/search.c

Null move pruning can reduce the depth down to a quiescence search, so the trick can be used here too to save some time.
Also a few code cleanups and switch to using info encoded directly in the move rather than looking up on the board.
ELO   | 2.36 +- 2.46 (95%)
GAMES | N: 41008 W: 11135 L: 10856 D: 19017

Use the null move eval trick in QS as well

---

src/evaluate.c
src/tuner/tuner.c
src/tuner/tuner.h

Bonus for passed pawn when opponent isn't attacking the square ahead.
ELO   | 3.93 +- 3.73 (95%)
GAMES | N: 17664 W: 4803 L: 4603 D: 8258
ELO   | 3.26 +- 3.21 (95%)
GAMES | N: 21960 W: 5459 L: 5253 D: 11248

Passed Pawn free to advance

---

src/search.c

ELO   | 3.52 +- 3.45 (95%)
GAMES | N: 20728 W: 5621 L: 5411 D: 9696
ELO   | 2.60 +- 2.67 (95%)
GAMES | N: 31568 W: 7785 L: 7549 D: 16234

RFP only when no TT move or TT move has good history

---

src/search.c

And score mated positions correctly. Tested with simplification bounds as I want this change even if it doesn't gain elo.
ELO   | -0.56 +- 2.71 (95%)
LLR   | 2.96 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 34400 W: 9336 L: 9391 D: 15673
ELO   | 0.64 +- 3.46 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 18888 W: 4643 L: 4608 D: 9637

Quiescence: Try all moves in check

---

src/search.c

ELO   | -0.29 +- 2.14 (95%)
GAMES | N: 54472 W: 14672 L: 14717 D: 25083

Avoid extending in root

---

src/time.c

When allowing double extensions, sometimes depth 1 will not finish before time is checked, and at very short time controls this can lead to aborting the search without having decided on a move to play. This change ensures depth 1 finished so there is a move chosen.

Ensure depth 1 finishes

---

src/board.c

ELO   | 2.42 +- 2.52 (95%)
GAMES | N: 39440 W: 10811 L: 10536 D: 18093
ELO   | 3.93 +- 3.69 (95%)
GAMES | N: 16784 W: 4251 L: 4061 D: 8472

Use separate piece values for SEE

---

src/search.c

ELO   | 2.55 +- 2.63 (95%)
GAMES | N: 36208 W: 9924 L: 9658 D: 16626
ELO   | 2.45 +- 2.53 (95%)
GAMES | N: 35760 W: 8994 L: 8742 D: 18024

Tweak SEE pruning

---

src/history.h

ELO   | 4.04 +- 3.81 (95%)
GAMES | N: 17120 W: 4689 L: 4490 D: 7941
ELO   | 3.35 +- 3.25 (95%)
GAMES | N: 21392 W: 5327 L: 5121 D: 10944

Tweak history update formula for quiet moves

---

src/history.h

Also moves at root/ply 1.
Stopped STC at 70k games, LTC passed simplification and failed gainer bounds.
ELO   | 1.17 +- 1.86 (95%)
LLR   | 0.00 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 71624 W: 19233 L: 18991 D: 33400
ELO   | 4.00 +- 4.97 (95%)
GAMES | N: 9296 W: 2356 L: 2249 D: 4691

Allow continuation history for null moves

---

src/evaluate.c
src/tuner/tuner.c
src/tuner/tuner.h

Used to only penalize doubled pawns when directly in front of each other, this adds a penalty also when there is one square between them.
ELO   | 3.62 +- 3.53 (95%)
GAMES | N: 19968 W: 5480 L: 5272 D: 9216
ELO   | 1.62 +- 1.56 (95%)
GAMES | N: 92200 W: 22500 L: 22071 D: 47629

Doubled pawns also with some distance

---

src/search.c

ELO   | 0.57 +- 1.76 (95%)
LLR   | -2.95 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 80536 W: 21708 L: 21575 D: 37253
ELO   | 2.04 +- 2.12 (95%)
GAMES | N: 50160 W: 12344 L: 12049 D: 25767

Store checkmated and stalemated positions in TT

---

src/search.c
src/transposition.c
src/transposition.h
src/uci.c

Bucket size 2, age and bound stored together as a uint8_t. Improves strength when TT is small (in context of the time control). Otherwise seems to be a wash.
Tests with smaller than normal TT size (for Weiss).
ELO   | 6.54 +- 5.23 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=8MB
GAMES | N: 9136 W: 2550 L: 2378 D: 4208
ELO   | 2.23 +- 2.32 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
GAMES | N: 41720 W: 10255 L: 9987 D: 21478

Implement buckets and aging for TT

---

src/search.c

Should be more or less the same, but there's some chance a different thread overwrites the entry for the same position with a different move, in which case using it and the other info is relevant.

Change TT probing when proving singularity

---

src/search.c

ELO   | 2.88 +- 2.93 (95%)
GAMES | N: 28760 W: 7770 L: 7532 D: 13458
ELO   | 4.82 +- 4.19 (95%)
GAMES | N: 12696 W: 3149 L: 2973 D: 6574

LMR more when few pieces are left

---

src/pyrrhic/tbprobe.c

Fix mapping offset for wide DTZ tables.
Advice that the memory access pattern for TBs is random.

Pyrrhic fixes

---

src/search.c

ELO   | 4.52 +- 4.10 (95%)
GAMES | N: 14376 W: 3856 L: 3669 D: 6851
ELO   | 4.78 +- 4.20 (95%)
GAMES | N: 12856 W: 3235 L: 3058 D: 6563

Adjust RFP margin by previous moves history score

---

src/search.c

Simplification.
ELO   | 0.15 +- 2.57 (95%)
GAMES | N: 37104 W: 9839 L: 9823 D: 17442
ELO   | 0.18 +- 2.45 (95%)
LLR   | 2.99 (-2.94, 2.94) [-4.00, 1.00]
GAMES | N: 37224 W: 9003 L: 8984 D: 19237

Remove depth condition for NMP

---

src/transposition.h

Non-regression bounds:
ELO   | 6.82 +- 6.34 (95%)
GAMES | N: 6064 W: 1657 L: 1538 D: 2869

Change TT indexing to use 128 bit multiplication

---

src/query/query.c

%20 is technically the correct replacement for spaces, but + is supported by both lichess and dbcn so, for now at least, it doesn't matter.

Use + instead of %20 in queries so the url is more humanly readable

---

src/movepicker.c
src/movepicker.h
src/search.c

ELO   | 2.63 +- 2.71 (95%)
GAMES | N: 33152 W: 8845 L: 8594 D: 15713
ELO   | 3.01 +- 3.01 (95%)
GAMES | N: 24552 W: 6025 L: 5812 D: 12715

Play TT move in QSearch

---

src/search.c
src/threads.c
src/threads.h

ELO   | 2.15 +- 2.22 (95%)
GAMES | N: 49632 W: 13297 L: 12990 D: 23345
ELO   | 2.52 +- 2.58 (95%)
GAMES | N: 32856 W: 7887 L: 7649 D: 17320

Separate continuation history for captures and non-captures

---

src/search.c

ELO   | 4.75 +- 4.24 (95%)
GAMES | N: 13456 W: 3612 L: 3428 D: 6416
ELO   | 6.20 +- 4.93 (95%)
GAMES | N: 9240 W: 2329 L: 2164 D: 4747

Reduce depth for cut nodes with no TT move

---

src/search.c
src/threads.c
src/threads.h

ELO   | 2.95 +- 2.97 (95%)
GAMES | N: 25056 W: 6077 L: 5864 D: 13115

Separate continuation history for positions in check and not

---

src/search.c

Simplification bounds:
ELO   | 6.18 +- 5.85 (95%)
GAMES | N: 6520 W: 1630 L: 1514 D: 3376

Simplify away LMP of noisy moves

---

src/uci.h

Weiss crashes when a game gets to about 800 moves and the position command with all the moves exceeds 4096 bytes. Now crashes around 1600 moves instead which I think is theoretically reachable but so unlikely I won't bother with until it happens once.

Increase input buffer to 8192 bytes

---

src/board.h
src/search.c

https://tcec-chess.com/#game=2&round=fl&season=cup11 in the tcec game between stockfish and leela weiss often reports 0.0 as the score because it sees a repetition in 1 and thinks the game can be drawn while it actually cant be, this patch increases the required repetition for pvnodes to 2. You might want to test this on OB for non regression though...
Bench: 17776946
also while testing this i encountered this
```
position fen k4q2/5r2/Pp1p1r2/1PpPp1b1/4P1P1/2R2PB1/6Rp/5Q1K b - - 65 179
go
info depth 1 seldepth 6 multipv 1 score cp 37 time 0 nodes 44 nps 44000 tbhits 0 hashfull 0 pv f6f3
info depth 2 seldepth 6 multipv 1 score cp 37 time 3 nodes 87 nps 21750 tbhits 0 hashfull 0 pv f6f3 c3f3
info depth 3 seldepth 6 multipv 1 score cp 37 time 7 nodes 137 nps 17125 tbhits 0 hashfull 0 pv …
```

better repetition scores

---

src/search.c

ELO   | 2.51 +- 4.29 (95%)
GAMES | N: 13152 W: 3487 L: 3392 D: 6273
ELO   | 1.15 +- 3.26 (95%)
GAMES | N: 20872 W: 5055 L: 4986 D: 10831

No NMP if static eval is below beta

---

src/movegen.c

ELO   | 12.17 +- 7.39 (95%)
GAMES | N: 4400 W: 1219 L: 1065 D: 2116

Avoid generating non-blocking quiet moves when in check

---

src/search.c

ELO   | 2.97 +- 2.99 (95%)
GAMES | N: 26912 W: 7095 L: 6865 D: 12952

Prefetch TT entries in QS too

---

src/search.c

ELO   | 11.48 +- 7.26 (95%)
GAMES | N: 4784 W: 1382 L: 1224 D: 2178
ELO   | 3.23 +- 3.17 (95%)
GAMES | N: 22072 W: 5405 L: 5200 D: 11467

Singular Extension at lower depths

---

src/search.c

ELO   | 2.25 +- 2.34 (95%)
GAMES | N: 43760 W: 11463 L: 11180 D: 21117
ELO   | 2.36 +- 2.44 (95%)
GAMES | N: 36816 W: 8882 L: 8632 D: 19302

Singular extension at yet lower depths

---

src/search.c

Passed STC, failed LTC as a gainer, but I like it and it would pass non-regression.
ELO   | 2.28 +- 2.35 (95%)
GAMES | N: 43512 W: 11489 L: 11204 D: 20819
ELO   | -0.56 +- 2.76 (95%)
LLR   | -2.97 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 28656 W: 6729 L: 6775 D: 15152

Skip pruning directly after a null move

---

src/evaluate.c
src/tuner/tuner.c
src/tuner/tuner.h

ELO   | 1.70 +- 1.64 (95%)
GAMES | N: 90992 W: 24283 L: 23838 D: 42871
ELO   | 3.52 +- 3.35 (95%)
GAMES | N: 19656 W: 4790 L: 4591 D: 10275

Penalize having pawns on the same color as own bishop

---

.github/workflows/make.yml

Tests more compilations and also verifies bench.
Commit messages must now have a bench node count in them. This also makes it easier to create tests on OB.
Bench: 19785851

Improve github actions

---

src/search.c
src/transposition.c
src/transposition.h

ELO   | 5.89 +- 4.85 (95%)
GAMES | N: 10264 W: 2766 L: 2592 D: 4906
ELO   | 4.28 +- 3.87 (95%)
GAMES | N: 14600 W: 3541 L: 3361 D: 7698
Bench: 18855972

Store static eval in TT

---

src/search.c

Reduce search depth if not singular, not able to multi-cut and ttScore is higher than beta.
ELO   | 2.66 +- 2.73 (95%)
GAMES | N: 31912 W: 8333 L: 8089 D: 15490
ELO   | 3.14 +- 3.10 (95%)
GAMES | N: 22768 W: 5496 L: 5290 D: 11982
Bench: 18662912

Singular Extension negative extensions

---

src/search.c
src/threads.h

ELO   | 11.52 +- 7.15 (95%)
GAMES | N: 4648 W: 1269 L: 1115 D: 2264
ELO   | 11.18 +- 6.84 (95%)
GAMES | N: 4664 W: 1173 L: 1023 D: 2468

Double singular extension in non-pv nodes when other moves are much worse

---

src/movepicker.c
src/movepicker.h
src/search.c

ELO   | 5.37 +- 4.51 (95%)
LLR   | 3.02 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 11528 W: 3012 L: 2834 D: 5682
ELO   | 2.05 +- 2.13 (95%)
GAMES | N: 47688 W: 11303 L: 11021 D: 25364

ProbCut: Only try moves which SEE allow it to beat probCutBeta

---

src/search.c

ELO   | 0.10 +- 2.27 (95%)
LLR   | -2.96 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 45920 W: 11760 L: 11747 D: 22413
ELO   | 9.21 +- 6.14 (95%)
GAMES | N: 5848 W: 1468 L: 1313 D: 3067
Bench: 20229272

Adjust lmrDepth used for pruning by the history score

---

src/search.c

ELO   | 2.61 +- 2.70 (95%)
GAMES | N: 32712 W: 8544 L: 8298 D: 15870
ELO   | 8.92 +- 6.02 (95%)
GAMES | N: 6040 W: 1508 L: 1353 D: 3179

Update continuation histories after LMR

---

src/search.c

ELO   | 0.56 +- 2.89 (95%)
LLR   | 2.99 (-2.94, 2.94) [-4.00, 1.00]
GAMES | N: 28496 W: 7374 L: 7328 D: 13794
ELO   | -0.63 +- 1.46 (95%)
GAMES | N: 102904 W: 24299 L: 24486 D: 54119
Bench: 20747862

Remove depth condition for using aspiration window and trend

---

src/search.c

ELO   | 0.34 +- 2.72 (95%)
GAMES | N: 32248 W: 8345 L: 8313 D: 15590
ELO   | 0.34 +- 2.58 (95%)
GAMES | N: 32752 W: 7755 L: 7723 D: 17274

Clean up LMR cont history updates

---

src/search.c

ELO   | 0.74 +- 2.38 (95%)
GAMES | N: 42464 W: 11090 L: 11000 D: 20374
ELO   | 3.95 +- 3.76 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 0.00]
GAMES | N: 15552 W: 3784 L: 3607 D: 8161
Bench: 19982072

Simplify away LMR depth adjustment for killers

---

src/search.c

ELO   | 2.87 +- 3.48 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 0.00]
GAMES | N: 20088 W: 5363 L: 5197 D: 9528
ELO   | 1.65 +- 2.78 (95%)
GAMES | N: 28496 W: 6847 L: 6712 D: 14937
Bench: 19339527

Increase LMR for all moves when TT move is a capture

---

src/search.c

ELO   | 1.56 +- 1.10 (95%)
LLR   | 2.97 (-2.94, 2.94) [-0.00, 3.00]
GAMES | N: 198752 W: 52044 L: 51152 D: 95556
ELO   | 1.70 +- 1.32 (95%)
GAMES | N: 127176 W: 30571 L: 29948 D: 66657
Bench: 20323233

Adjust aspi window delta by previous depth's score

---

src/search.c

ELO   | -0.72 +- 1.13 (95%)
GAMES | N: 186496 W: 47953 L: 48339 D: 90204
Bench: 20323233

Remove aspiration window adjustment for extreme scores

---

src/move.h

Avoids generating some illegal castling moves, as well as slightly lowering the chance of using illegal moves from TT and killers.
Bench:  19389515

Check that the king doesn't end in check for pseudo-legality of castling

---

src/move.c
src/move.h
src/movegen.c

This means any castling move generated or validated for pseudo-legality is fully legal.
Bench: 19389515

Fully validate legality of castling moves

---

src/move.c
src/movegen.c

ELO   | -0.38 +- 1.51 (95%)
GAMES | N: 105008 W: 27193 L: 27308 D: 50507
Bench: 19891416

Stricter pseudo-legality test and movegen

---

src/uci.c

Before this patch, Weiss adds an extra newline after 'bestmove'. For example:
```
$ ./weiss
> go depth 1
< info depth 1 seldepth 1 multipv 1 score cp 68 time 0 nodes 49 nps 49000 tbhits 0 hashfull 0 pv b1c3
< bestmove b1c3
<
```
where:
```
>  input to engine
<  output from engine
```
However, the additional empty line after bestmove makes python-chess unhappy. With this simple repro:
```
$ python3
import chess.engine
engine = chess.engine.SimpleEngine.popen_uci('./weiss') board = chess.Board()
result = engine.analyse(board, chess.engine.Limit(time=1)) # triggers the assert result['score']
engine.quit()
```
I get:
```
Exception in callback Protocol._line_received('')
handle: <Handle Protocol._line_received('')>
Traceback (most recent call last):
File …
```

Improve UCI compliance: remove extra newline after 'bestmove'

---

src/pyrrhic/tbchess.c
src/pyrrhic/tbprobe.c

GCC 13 has made checks for mixed-signedness comparisons more stringent, causing a build failure on Ubuntu 23.10 (pre-release). Workaround this by adding some casts in the Pyrrhic code.
Fixes #677
**
Note: This is perhaps not the cleanest possible fix, but it is the smallest one. Possibly, a better fix would be something such as:
```
typedef enum {
PYRRHIC_BLACK   = 0, PYRRHIC_WHITE   = 1,
PYRRHIC_PAWN    = 1, PYRRHIC_KNIGHT  = 2,
PYRRHIC_BISHOP  = 3, PYRRHIC_ROOK    = 4,
PYRRHIC_QUEEN   = 5, PYRRHIC_KING    = 6
} PyrrhicPieces;
for (PyrrhicPieces i = PYRRHIC_PAWN; i <= PYRRHIC_KING; i++)
{
...
}
```
That is, break the big anonymous enum type to smaller enum types of related values. That would allow for more consistent use of types in expressions. However, I'm not …

Fix mixed-signedness comparison

---

src/board.h
src/search.c

ELO   | -0.20 +- 1.58 (95%)
GAMES | N: 88408 W: 21063 L: 21115 D: 46230
Bench: 20282767

Revert to using 2-fold repetition for all nodes

---

src/search.c

ELO   | 6.10 +- 3.85 (95%)
GAMES | N: 16232 W: 4374 L: 4089 D: 7769
ELO   | 2.38 +- 1.90 (95%)
GAMES | N: 60800 W: 14660 L: 14244 D: 31896
Bench: 21253689

LMR earlier for quiet moves

---

src/search.c

ELO   | -0.08 +- 1.79 (95%)
GAMES | N: 74752 W: 19383 L: 19400 D: 35969
ELO   | -0.22 +- 1.56 (95%)
GAMES | N: 89984 W: 21283 L: 21340 D: 47361
Bench: 19385842

Simplify away improving in RFP formula

---

src/search.c

Elo   | 1.66 +- 1.24 (95%)
Games | N: 155362 W: 40426 L: 39682 D: 75254
http://chess.grantnet.us/test/34079/
Elo   | 1.53 +- 1.55 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 3.00]
Games | N: 88130 W: 20407 L: 20018 D: 47705
Penta | [557, 10485, 21670, 10718, 635]
http://chess.grantnet.us/test/34098/
Bench: 18586766

Lower the returned score from ProbCut

---

src/search.c

Elo   | 1.06 +- 1.28 (95%)
LLR   | 0.89 (-2.25, 2.89) [0.00, 3.00]
Games | N: 144396 W: 37138 L: 36699 D: 70559
Penta | [2119, 17567, 32521, 17738, 2253]
http://chess.grantnet.us/test/34156/
Elo   | 6.22 +- 4.32 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.00]
Games | N: 11628 W: 2829 L: 2621 D: 6178
Penta | [71, 1293, 2890, 1477, 83]
http://chess.grantnet.us/test/34170/
Bench: 19885655

LMR reduce more in cut nodes

---

src/evaluate.c
src/history.h
src/movepicker.c
src/search.c

STC 80k vs master
Elo   | 9.96 +- 3.47 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=32MB
Games | N: 20000 W: 5506 L: 4933 D: 9561
Penta | [263, 2248, 4501, 2629, 359]
http://chess.grantnet.us/test/34247/
LTC 38k vs master
Elo   | 7.29 +- 4.71 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.00]
Games | N: 9770 W: 2393 L: 2188 D: 5189
Penta | [52, 1107, 2392, 1252, 82]
http://chess.grantnet.us/test/34217/
LTC 80k vs 38k
Elo   | 3.02 +- 2.73 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 3.00]
Games | N: 29264 W: 7003 L: 6749 D: 15512
Penta | [192, 3480, 7077, 3648, 235]
http://chess.grantnet.us/test/34244/
Bench: 21740192

SPSA tune search, king safety, and history update

---

src/search.c
src/threads.c
src/threads.h

Elo   | 1.75 +- 2.94 (95%)
LLR   | 2.90 (-2.25, 2.89) [-3.00, 0.00]
Games | N: 24822 W: 5834 L: 5709 D: 13279
Penta | [180, 2920, 6096, 3025, 190]
http://chess.grantnet.us/test/34274/
Bench: 21963671

Remove null mover LMR adjustment

---

src/evaluate.c
src/history.h
src/movepicker.c
src/search.c

Elo   | 5.67 +- 2.46 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=32MB
Games | N: 40006 W: 10812 L: 10159 D: 19035
Penta | [592, 4628, 9013, 5075, 695]
http://chess.grantnet.us/test/34396/
Elo   | 2.14 +- 2.15 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.00]
Games | N: 48152 W: 11690 L: 11393 D: 25069
Penta | [364, 5618, 11799, 5947, 348]
http://chess.grantnet.us/test/34392/
Bench: 34121414

SPSA tune search, king safety, history updates, tempo

---

src/search.c

Elo   | 1.73 +- 1.67 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.00]
Games | N: 87720 W: 23345 L: 22907 D: 41468
Penta | [1400, 10534, 19626, 10828, 1472]
http://chess.grantnet.us/test/34414/
Elo   | 1.68 +- 1.72 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.00]
Games | N: 74682 W: 18022 L: 17661 D: 38999
Penta | [533, 8844, 18281, 9095, 588]
http://chess.grantnet.us/test/34418/
Bench: 30658368

Reintroduce improving into the RFP condition

---

src/evaluate.c
src/history.h
src/movepicker.c
src/search.c

Elo   | 0.55 +- 1.93 (95%)
LLR   | -0.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 65634 W: 17356 L: 17252 D: 31026
Penta | [1090, 7901, 14721, 8025, 1080]
http://chess.grantnet.us/test/34493/
Elo   | 5.78 +- 4.09 (95%)
Games | N: 13174 W: 3246 L: 3027 D: 6901
Penta | [96, 1485, 3216, 1684, 106]
http://chess.grantnet.us/test/34494/
Bench: 28419588

Separate formula for history bonus/malus and SPSA tuning

---

src/evaluate.c

Elo   | 1.19 +- 2.65 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 34614 W: 9130 L: 9011 D: 16473
Penta | [573, 4142, 7743, 4291, 558]
http://chess.grantnet.us/test/34511/
Elo   | 1.19 +- 2.62 (95%)
Games | N: 32284 W: 7808 L: 7697 D: 16779
Penta | [242, 3834, 7866, 3971, 229]
http://chess.grantnet.us/test/34514/
Bench: 27258264

Remove influence of open lines to the king on king safety

---

src/movepicker.c

Elo   | 1.61 +- 1.53 (95%)
Games | N: 103528 W: 27279 L: 26799 D: 49450
Penta | [1652, 12341, 23313, 12791, 1667]
http://chess.grantnet.us/test/34528/
Elo   | 2.50 +- 2.38 (95%)
Games | N: 38830 W: 9345 L: 9066 D: 20419
Penta | [294, 4504, 9520, 4823, 274]
http://chess.grantnet.us/test/34539/
Bench: 29925582

Adjust the history thresholds for good noisy moves based on depth

---

src/board.c
src/pyrrhic/tbconfig.h
src/syzygy.h
src/types.h

WHITE is now 0 and BLACK is 1, matching the majority of engines.
Bench: 29925582

Swap the value of BLACK and WHITE

---

src/search.c

Elo   | 1.77 +- 2.98 (95%)
LLR   | 3.00 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 27542 W: 7336 L: 7196 D: 13010
Penta | [435, 3333, 6129, 3405, 469]
http://chess.grantnet.us/test/34547/
Elo   | 0.64 +- 2.24 (95%)
Games | N: 44394 W: 10748 L: 10666 D: 22980
Penta | [313, 5264, 10978, 5312, 330]
http://chess.grantnet.us/test/34551/
Bench: 32148915

Use history Malus formula when penalizing bad LMR re-search

---

src/history.h
src/threads.c
src/threads.h

Elo   | 4.30 +- 3.35 (95%)
Games | N: 21672 W: 5826 L: 5558 D: 10288
Penta | [339, 2546, 4823, 2764, 364]
http://chess.grantnet.us/test/34696/
Elo   | 1.89 +- 1.92 (95%)
Games | N: 59734 W: 14432 L: 14107 D: 31195
Penta | [378, 7041, 14763, 7248, 437]
http://chess.grantnet.us/test/34702/
Bench: 21514164

Add pawn structure history

---

src/search.c

Elo   | 1.83 +- 1.75 (95%)
Games | N: 78896 W: 20869 L: 20454 D: 37573
Penta | [1205, 9464, 17758, 9753, 1268]
http://chess.grantnet.us/test/34716/
Elo   | 1.17 +- 1.09 (95%)
Games | N: 185070 W: 44541 L: 43920 D: 96609
Penta | [1259, 21981, 45468, 22534, 1293]
http://chess.grantnet.us/test/34726/
Bench: 21825554

Give a bonus to pawn history of moves that cause a TT cut

---

src/history.h
src/movepicker.c
src/search.c

Elo   | -2.83 +- 3.55 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 3.00]
Games | N: 19368 W: 5024 L: 5182 D: 9162
Penta | [312, 2473, 4268, 2323, 308]
http://chess.grantnet.us/test/34887/
Elo   | 3.41 +- 3.00 (95%)
Games | N: 24736 W: 6083 L: 5840 D: 12813
Penta | [160, 2858, 6109, 3061, 180]
http://chess.grantnet.us/test/34874/

SPSA tune search, history updates

---

src/evaluate.c

Elo   | 2.38 +- 1.86 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 53310 W: 14695 L: 14330 D: 24285
Penta | [987, 6431, 11527, 6650, 1060]
http://chess.grantnet.us/test/38169/
Elo   | 2.67 +- 2.00 (95%)
Games | N: 36584 W: 9157 L: 8876 D: 18551
Penta | [324, 4296, 8797, 4525, 350]
http://chess.grantnet.us/test/38198/
Bench: 24215677

Only count pawns in the center for bad pawns with bishops

---

src/history.h
src/search.c
src/threads.c
src/threads.h

Original idea from Caissa, implementation mainly inspired by Stockfish.
Elo   | 4.87 +- 3.10 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 19484 W: 5549 L: 5276 D: 8659
Penta | [365, 2281, 4245, 2418, 433]
http://chess.grantnet.us/test/38269/
Elo   | 11.70 +- 4.81 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 6092 W: 1632 L: 1427 D: 3033
Penta | [37, 655, 1482, 810, 62]
http://chess.grantnet.us/test/38270/
Bench: 24198920

Add eval correction based on pawn structure eval history

---

src/history.h
src/threads.c
src/threads.h

Original idea from Caissa, implementation mainly inspired by Stockfish.
Elo   | 3.02 +- 2.23 (95%)
LLR   | 3.06 (-2.94, 2.94) [0.00, 3.00]
Games | N: 37948 W: 10612 L: 10282 D: 17054
Penta | [724, 4518, 8282, 4604, 846]
http://chess.grantnet.us/test/38271/
Elo   | 7.88 +- 3.89 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 9520 W: 2477 L: 2261 D: 4782
Penta | [49, 1124, 2251, 1234, 102]
http://chess.grantnet.us/test/38277/
Bench: 26539847

Add eval correction based on material eval history

---

src/history.h
src/movepicker.c
src/search.c

Elo   | 14.83 +- 5.79 (95%)
Games | N: 5390 W: 1601 L: 1371 D: 2418
Penta | [90, 561, 1181, 755, 108]
http://chess.grantnet.us/test/38337/
Elo   | 10.41 +- 4.55 (95%)
Games | N: 6914 W: 1844 L: 1637 D: 3433
Penta | [43, 765, 1666, 908, 75]
http://chess.grantnet.us/test/38321/

SPSA tune search and history

---

src/search.c

Mate scores should now always have a PV all the way to the mated position.

Update PV with QSearch moves

---

src/history.h
src/movepicker.c
src/movepicker.h
src/search.c
src/threads.h

Elo   | 1.64 +- 2.52 (95%)
Games | N: 29006 W: 7952 L: 7815 D: 13239
Penta | [585, 3429, 6284, 3674, 531]
http://chess.grantnet.us/test/38358/
Elo   | 2.25 +- 2.60 (95%)
Games | N: 21662 W: 5474 L: 5334 D: 10854
Penta | [172, 2633, 5107, 2721, 198]
http://chess.grantnet.us/test/38363/
Bench: 23301226

Simplify down to only 1 killer move

---

src/search.c

Elo   | -0.38 +- 1.15 (95%)
Games | N: 134820 W: 36505 L: 36654 D: 61661
Penta | [2445, 16374, 29890, 16287, 2414]
http://chess.grantnet.us/test/38360/
Bench: 25382999

Guard against using TB and mate scores as eval

---

src/search.c

While a normal score found through probcut is less reliable due to the reduced depth, a terminal score found through probcut is proven despite reduced depth.
Elo   | 1.24 +- 2.25 (95%)
Games | N: 33400 W: 9206 L: 9087 D: 15107
Penta | [531, 3852, 7851, 3899, 567]
http://chess.grantnet.us/test/38370/
Bench: 25382999

Return exact terminal scores from probcut

---

src/history.h
src/search.c
src/threads.c
src/threads.h

Elo   | 1.79 +- 1.43 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 88644 W: 24280 L: 23823 D: 40541
Penta | [1632, 10637, 19381, 10986, 1686]
http://chess.grantnet.us/test/38443/
Elo   | 1.72 +- 1.38 (95%)
Games | N: 74734 W: 18763 L: 18394 D: 37577
Penta | [610, 8865, 18046, 9238, 608]
http://chess.grantnet.us/test/38444/
Bench: 23375239

Add eval correction based on continuation history

---

src/history.h
src/search.c
src/transposition.c

Elo   | 2.95 +- 2.20 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 3.00]
Games | N: 37080 W: 10197 L: 9882 D: 17001
Penta | [642, 4398, 8207, 4589, 704]
http://chess.grantnet.us/test/38471/
Elo   | 4.64 +- 2.84 (95%)
Games | N: 17154 W: 4375 L: 4146 D: 8633
Penta | [131, 1922, 4250, 2135, 139]
http://chess.grantnet.us/test/38480/
Bench: 23040214

Add eval correction based on continuation history [-3][-1], and tweak TT replacement and singular extension beta

---

src/history.h

Elo   | 1.41 +- 1.07 (95%)
Games | N: 156536 W: 42759 L: 42125 D: 71652
Penta | [2782, 18776, 34643, 19160, 2907]
http://chess.grantnet.us/test/38482/
Elo   | 4.14 +- 2.66 (95%)
Games | N: 19460 W: 4913 L: 4681 D: 9866
Penta | [122, 2247, 4803, 2393, 165]
http://chess.grantnet.us/test/38486/
Bench: 22789257

Add eval correction based on continuation history [-4][-1]

---

src/evaluate.c
src/history.h
src/movepicker.c
src/search.c

STC 10k vs master
Elo   | 2.36 +- 1.86 (95%)
Games | N: 52918 W: 14493 L: 14134 D: 24291
Penta | [943, 6341, 11635, 6494, 1046]
http://chess.grantnet.us/test/38500/
LTC 5k vs master
Elo   | 4.46 +- 2.80 (95%)
Games | N: 18072 W: 4596 L: 4364 D: 9112
Penta | [131, 2101, 4359, 2295, 150]
http://chess.grantnet.us/test/38495/
LTC 10k vs 5k
Elo   | 1.91 +- 1.52 (95%)
Games | N: 60484 W: 15163 L: 14831 D: 30490
Penta | [448, 7172, 14683, 7478, 461]
http://chess.grantnet.us/test/38498/
Bench: 27273376

SPSA tune search and history 

---

src/movepicker.c

Elo   | 3.83 +- 3.41 (95%)
Games | N: 15606 W: 4341 L: 4169 D: 7096
Penta | [264, 1862, 3428, 1936, 313]
http://chess.grantnet.us/test/38502/
Elo   | 5.98 +- 3.81 (95%)
Games | N: 9592 W: 2476 L: 2311 D: 4805
Penta | [64, 1084, 2353, 1213, 82]
http://chess.grantnet.us/test/38505/
Bench: 27857429

Simplify movepicker noisy move valuation formula

---

src/search.c

Elo   | 1.44 +- 2.39 (95%)
Games | N: 31112 W: 8485 L: 8356 D: 14271
Penta | [538, 3731, 6918, 3802, 567]
http://chess.grantnet.us/test/38503/
Elo   | 0.46 +- 1.67 (95%)
Games | N: 50914 W: 12704 L: 12637 D: 25573
Penta | [396, 6127, 12359, 6164, 411]
http://chess.grantnet.us/test/38506/
Bench: 30209528

Simplify SEE pruning to use same threshold for quiet and noisy moves

---

src/history.h
src/threads.c

Elo   | 1.90 +- 1.53 (95%)
Games | N: 77364 W: 21201 L: 20779 D: 35384
Penta | [1342, 9377, 16952, 9539, 1472]
http://chess.grantnet.us/test/38501/
Elo   | 1.98 +- 1.57 (95%)
Games | N: 56852 W: 14287 L: 13963 D: 28602
Penta | [405, 6796, 13767, 6986, 472]
http://chess.grantnet.us/test/38508/
Bench: 27491945

Add eval correction based on continuation history [-5][-1]

---

src/history.h
src/threads.c

Elo   | 3.29 +- 2.39 (95%)
Games | N: 31726 W: 8816 L: 8516 D: 14394
Penta | [569, 3715, 7073, 3859, 647]
http://chess.grantnet.us/test/38511/
Elo   | 3.95 +- 2.59 (95%)
Games | N: 21038 W: 5434 L: 5195 D: 10409
Penta | [155, 2438, 5130, 2605, 191]
http://chess.grantnet.us/test/38512/
Bench: 25653283

Add eval correction based on continuation history [-6][-1] and [-7][-1]

---

src/search.c

Elo   | 2.42 +- 1.90 (95%)
Games | N: 50044 W: 13792 L: 13443 D: 22809
Penta | [871, 6033, 10950, 6212, 956]
http://chess.grantnet.us/test/38515/
Elo   | 2.75 +- 2.03 (95%)
Games | N: 34018 W: 8636 L: 8367 D: 17015
Penta | [258, 3962, 8324, 4183, 282]
http://chess.grantnet.us/test/38517/
Bench: 25107463

Use TT score as eval when it is more informative

---

src/search.c

Elo   | 3.86 +- 2.66 (95%)
Games | N: 25486 W: 7128 L: 6845 D: 11513
Penta | [446, 3016, 5562, 3247, 472]
http://chess.grantnet.us/test/38535/
Elo   | 1.49 +- 1.20 (95%)
Games | N: 98118 W: 24626 L: 24205 D: 49287
Penta | [793, 11557, 23866, 12122, 721]
http://chess.grantnet.us/test/38536/
Bench: 22540657

Reduce depth of NMP searches more

---

src/search.c

Elo   | -0.28 +- 1.24 (95%)
LLR   | 3.00 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 115826 W: 31239 L: 31334 D: 53253
Penta | [2064, 14132, 25617, 14035, 2065]
http://chess.grantnet.us/test/38542/
Elo   | 1.87 +- 2.41 (95%)
Games | N: 24340 W: 6101 L: 5970 D: 12269
Penta | [176, 2935, 5837, 3026, 196]
http://chess.grantnet.us/test/38548/
Bench: 25023530

Simplify QS futility pruning to only skip on promotions instead of advanced pawn pushes

---

src/movepicker.c

Elo   | 0.93 +- 2.11 (95%)
Games | N: 39600 W: 10746 L: 10640 D: 18214
Penta | [681, 4778, 8779, 4878, 684]
http://chess.grantnet.us/test/38573/
Elo   | 0.18 +- 1.47 (95%)
Games | N: 64768 W: 16013 L: 15979 D: 32776
Penta | [469, 7861, 15709, 7857, 488]
http://chess.grantnet.us/test/38576/
Bench: 26587524

Simplify away depth dependence in NoisyGood formula

---

src/search.c
src/threads.h

Elo   | 11.37 +- 4.93 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 3.00]
Games | N: 7216 W: 2084 L: 1848 D: 3284
Penta | [102, 790, 1642, 918, 156]
http://chess.grantnet.us/test/38596/
Elo   | 11.76 +- 4.85 (95%)
Games | N: 6178 W: 1638 L: 1429 D: 3111
Penta | [54, 657, 1451, 880, 47]
http://chess.grantnet.us/test/38598/
Bench: 26587524

Adjust time spent based on how much of the search effort goes into the top move

---

src/search.c

Impacts the time management tweak that was added alongside this, but seems more or less neutral and tuning will surely fix it at a later point even if it is a loss right now.
Elo   | -0.58 +- 1.83 (95%)
LLR   | 0.68 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 51172 W: 13920 L: 14006 D: 23246
Penta | [854, 6055, 11836, 6005, 836]
http://chess.grantnet.us/test/38611/
Bench: 26587524

Fix node counts for root moves

---

src/movegen.c
src/movegen.h
src/search.c

Elo   | 0.18 +- 2.84 (95%)
Conf  | 8.0+0.08s Threads=1 Hash=32MB
Games | N: 21244 W: 5800 L: 5789 D: 9655
Penta | [369, 2456, 4950, 2489, 358]
http://chess.grantnet.us/test/38610/
Bench: 26587524

Properly handle checkmate occuring exactly when reaching the 50 move rule

---

src/search.c
src/transposition.h
src/types.h
src/uci.c

Small functional change allowing singular extensions to be attempted as long as the score from TT isn't a terminal score instead of requiring it to be below an arbitrary threshold.
Bench: 23851500

Add helper functions for dealing with terminal scores (mate, tb)

---

src/types.h

Affects only mate distance pruning. Thanks to @jherrera80 for pointing out the mistake.
Bench: 23851500

Fix incorrect mateIn(ply)

---

src/search.c
src/threads.c
src/threads.h

The old sort was meant to work with the previous way root moves were handled, they are now significantly different and so the sorting failed.
Elo   | 5.09 +- 3.80 (95%)
LLR   | 2.98 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 12366 W: 3589 L: 3408 D: 5369
Penta | [221, 1378, 2837, 1493, 254]
http://chess.grantnet.us/test/38616/
Bench: 23851500

Fix root move sorting

---

src/history.h

Elo   | 1.50 +- 2.43 (95%)
LLR   | 3.03 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 31520 W: 8838 L: 8702 D: 13980
Penta | [594, 3833, 6835, 3839, 659]
http://chess.grantnet.us/test/38638/
Bench: 24311257

Change the formula for combining correction histories

---

src/search.c
src/search.h
src/uci.c

Done due to CuteChess being too slow to parse the normal output.
Bench: 24311257

Add "Minimal" option where only info from the final search depth is printed

---

src/threads.c

Crashed when using more than 1 thread for some reason. Rewriting the comma-separated expressions fixes it.
Bench: 24311257

Fix SortRootMoves

---

src/search.c

Elo   | 1.32 +- 0.96 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 194686 W: 54098 L: 53358 D: 87230
Penta | [3590, 23161, 43118, 23867, 3607]
http://chess.grantnet.us/test/38655/
Elo   | 2.21 +- 1.72 (95%)
Games | N: 46386 W: 11960 L: 11665 D: 22761
Penta | [304, 5454, 11418, 5677, 340]
http://chess.grantnet.us/test/38659/
Bench: 25584908

Clear the killer move for child nodes

---

src/makemove.c
src/makemove.h
src/move.c
src/move.h
src/movegen.c
src/movegen.h
src/search.c
src/tests.c

Losing elo for now, but hopefully will recover most of it with tuning and future optimizations/speedups of the code.
Elo   | -3.03 +- 2.13 (95%)
Conf  | 10.0+0.10s Threads=1 Hash=32MB
Games | N: 40012 W: 10796 L: 11145 D: 18071
Penta | [740, 5074, 8729, 4721, 742]
http://chess.grantnet.us/test/38661/
Elo   | -7.65 +- 1.84 (95%)
Conf  | 60.0+0.60s Threads=1 Hash=128MB
Games | N: 40000 W: 9583 L: 10464 D: 19953
Penta | [310, 5177, 9813, 4484, 216]
http://chess.grantnet.us/test/38657/
Bench: 24472040

Check move legality at the beginning of the move loop

---

src/board.c
src/board.h
src/history.h
src/makemove.c
src/threads.c
src/threads.h

Elo   | 1.75 +- 1.41 (95%)
Games | N: 91182 W: 25296 L: 24837 D: 41049
Penta | [1656, 10875, 20093, 11288, 1679]
http://chess.grantnet.us/test/38670/
Elo   | 2.25 +- 1.75 (95%)
Games | N: 45420 W: 11777 L: 11483 D: 22160
Penta | [312, 5383, 11038, 5653, 324]
http://chess.grantnet.us/test/38677/
Bench: 25487944

Replace material correction history with minor/major correction history

---

src/search.c

Elo   | 1.46 +- 1.13 (95%)
Games | N: 145398 W: 41797 L: 41184 D: 62417
Penta | [2856, 17148, 32123, 17671, 2901]
http://chess.grantnet.us/test/38748/
Elo   | 1.61 +- 1.29 (95%)
Games | N: 83740 W: 22044 L: 21656 D: 40040
Penta | [620, 9936, 20405, 10254, 655]
http://chess.grantnet.us/test/38752/
Bench: 27558865

Only prune quiets based on history

---

src/search.c

Ignore the bound of the tt entry, so also lower bound scores can prevent trying ProbCut.
Elo   | 4.99 +- 3.82 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 12752 W: 3782 L: 3599 D: 5371
Penta | [250, 1451, 2812, 1592, 271]
http://chess.grantnet.us/test/38771/
Elo   | 0.13 +- 1.43 (95%)
Games | N: 68478 W: 17959 L: 17933 D: 32586
Penta | [503, 8341, 16558, 8301, 536]
http://chess.grantnet.us/test/38774/
Bench: 27237021

Simplify ProbCut condition
